'use strict';
const E=SomikResearch;
const $=id=>document.getElementById(id);
const fmt=(v,d=2)=>v!==null&&v!==undefined&&Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'—';
const pct=(v,d=1)=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(d)+'%':'—';
const nowIso=()=>new Date().toISOString();
let world=null,running=true,speed=100,renderEnabled=true,selectedId=null,brainMode='selected';
let importedEvents=[];
let runMeta={runId:'',createdAt:'',lastSaveAt:'',lastSaveTick:-1,eventSeq:0};
let db=null,lastMetrics=null,lastUiAt=0,lastDrawAt=0,lastAutosaveWall=0,lastAutosaveTick=0,lastPerfAt=performance.now(),ticksSincePerf=0,currentTPS=0,saveInFlight=null;
const AUTOSAVE_MS=30000,AUTOSAVE_TICKS=5000,ROLLING_SAVES=5;
const COLORS={agent:'#38bdf8',primary:'#fde047',waste:'#a78bfa',tissue:'#fb923c',object:'#94a3b8',corpse:'#b45309'};

function makeRunId(seed){return `R11-${seed}-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;}
function treatmentName(){return world?.treatment?.reproductionMode==='sexual'?'Open Evolution — sexual':'Control';}

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('somik-world-research-1-1',2);r.onupgradeneeded=()=>{const d=r.result,tx=r.transaction;let ss;if(!d.objectStoreNames.contains('snapshots'))ss=d.createObjectStore('snapshots',{keyPath:'key'});else ss=tx.objectStore('snapshots');if(!ss.indexNames.contains('savedAt'))ss.createIndex('savedAt','savedAt');if(!ss.indexNames.contains('runId'))ss.createIndex('runId','runId');let es;if(!d.objectStoreNames.contains('events'))es=d.createObjectStore('events',{keyPath:['runId','seq']});else es=tx.objectStore('events');if(!es.indexNames.contains('runId'))es.createIndex('runId','runId');if(!es.indexNames.contains('type'))es.createIndex('type','type');if(!es.indexNames.contains('child'))es.createIndex('child','child');if(!es.indexNames.contains('runChild'))es.createIndex('runChild',['runId','child']);if(!es.indexNames.contains('runType'))es.createIndex('runType',['runId','type']);if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IDB abort'));});}
function compactEvent(ev){
  if(!['birth','death','checkpoint','technical_failure'].includes(ev.type))return null;
  const out={...ev};delete out.runId;delete out.seq;return out;
}
async function saveNow(reason='manual'){
  if(!world)return false;
  if(saveInFlight){await saveInFlight;return saveNow(reason);}
  if(!db){lastAutosaveWall=Date.now();lastAutosaveTick=world.tick;return false;}
  const target=world,meta={...runMeta},sourceCount=target.eventBuffer.length,historyCount=importedEvents.length;
  const events=[...importedEvents,...target.eventBuffer.slice(0,sourceCount).map(compactEvent).filter(Boolean)];
  const savedAt=nowIso(),tick=target.tick,key=`${meta.runId}:${String(tick).padStart(14,'0')}`;
  const snapshot=JSON.parse(JSON.stringify(target.dump()));snapshot.eventBuffer=[];
  const savedMeta={...meta,lastSaveAt:savedAt,lastSaveTick:tick,eventSeq:meta.eventSeq+events.length};
  const record={key,runId:meta.runId,seed:target.seed,tick,savedAt,reason,engineHash:E.ENGINE_HASH,
    protocolHash:E.PROTOCOL_HASH,stateHash:target.stateHash(),snapshotHash:E.snapshotHash(snapshot),
    state:snapshot,appMeta:{...savedMeta,selectedId}};
  saveInFlight=(async()=>{try{
    // World, event sequence and event archive commit together or not at all.
    const tx=db.transaction(['events','snapshots','meta'],'readwrite'),done=txDone(tx);
    let seq=meta.eventSeq;for(const ev of events)tx.objectStore('events').put({...ev,runId:meta.runId,seq:++seq});
    tx.objectStore('snapshots').put(record);tx.objectStore('meta').put({key:'latest',snapshotKey:key});await done;
    target.eventBuffer.splice(0,sourceCount);importedEvents.splice(0,historyCount);
    if(world===target&&runMeta.runId===meta.runId){Object.assign(runMeta,savedMeta);lastAutosaveWall=Date.now();lastAutosaveTick=tick;
      $('saveStatus').className='saveOk';$('saveStatus').textContent=`✓ נשמר — ${new Date(savedAt).toLocaleTimeString('he-IL')} · tick ${fmt(tick,0)}`;}
    try{await pruneSnapshots(meta.runId);}catch(err){console.warn('Snapshot pruning:',err);}
    refreshArchiveUi();return true;
  }catch(err){lastAutosaveWall=Date.now();lastAutosaveTick=target.tick;
    $('saveStatus').className='saveWarn';$('saveStatus').textContent='⚠ השמירה נכשלה. ייצא קובץ גיבוי: '+((err&&err.message)||'transaction aborted');return false;
  }finally{saveInFlight=null;}})();return saveInFlight;
}
async function pruneSnapshots(runId){const tx=db.transaction('snapshots','readwrite'),idx=tx.objectStore('snapshots').index('runId'),req=idx.getAll(IDBKeyRange.only(runId));const rows=await reqPromise(req);rows.sort((a,b)=>b.tick-a.tick);for(const r of rows.slice(ROLLING_SAVES))tx.objectStore('snapshots').delete(r.key);await txDone(tx);}
function reqPromise(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function latestSnapshot(){if(!db)return null;const tx=db.transaction('snapshots'),idx=tx.objectStore('snapshots').index('savedAt'),req=idx.openCursor(null,'prev');return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result?.value||null);req.onerror=()=>reject(req.error);});}
async function loadSnapshotRecord(rec){if(rec.snapshotHash&&E.snapshotHash(rec.state)!==rec.snapshotHash)throw new Error('Snapshot checksum mismatch');const loaded=E.World.load(rec.state);if(rec.stateHash&&loaded.stateHash()!==rec.stateHash)throw new Error('Scientific state checksum mismatch');world=loaded;importedEvents=[];runMeta={...rec.appMeta,lastSaveAt:rec.savedAt,lastSaveTick:rec.tick,eventSeq:rec.appMeta?.eventSeq||0};selectedId=rec.appMeta?.selectedId||null;running=!world.extinct&&!world.technicalFailure;speed=Number($('speedSel').value)||100;lastAutosaveWall=Date.now();lastAutosaveTick=world.tick;updateRunIdentity();updatePauseUi();fullRefresh();}
async function loadSnapshotByKey(key){const tx=db.transaction('snapshots'),rec=await reqPromise(tx.objectStore('snapshots').get(key));if(!rec)return;const was=running;running=false;try{
  if(!await saveNow('before-load'))throw new Error('Save failed; current run retained');
  const entries=await getAllEvents(rec.runId);await loadSnapshotRecord(rec);running=false;
  const sourceRunId=runMeta.runId;runMeta={...runMeta,runId:makeRunId(world.seed),sourceRunId,createdAt:nowIso(),eventSeq:0,lastSaveTick:-1,lastSaveAt:''};
  importedEvents=entries.filter(e=>e.seq<=(rec.appMeta?.eventSeq||0)).map(compactEvent).filter(Boolean);
  await saveNow('fork-from-snapshot');updateRunIdentity();updatePauseUi();
}catch(err){running=was;updatePauseUi();alert(err.message);}}
async function countEvents(){if(!db||!runMeta.runId)return 0;const tx=db.transaction('events'),idx=tx.objectStore('events').index('runId');return await reqPromise(idx.count(IDBKeyRange.only(runMeta.runId)));}
async function getAllEvents(runId=runMeta.runId){if(!db)return[];const tx=db.transaction('events'),idx=tx.objectStore('events').index('runId');return await reqPromise(idx.getAll(IDBKeyRange.only(runId)));}
async function listRuns(){if(!db)return[];const tx=db.transaction('snapshots'),rows=await reqPromise(tx.objectStore('snapshots').getAll());const best=new Map();for(const r of rows){const x=best.get(r.runId);if(!x||r.tick>x.tick)best.set(r.runId,r);}return[...best.values()].sort((a,b)=>b.savedAt.localeCompare(a.savedAt));}
async function refreshStorageUi(){if(!$('storageInfo'))return;try{const est=await navigator.storage?.estimate?.(),persisted=await navigator.storage?.persisted?.();const usage=est?.usage??0,quota=est?.quota??0;$('storageInfo').innerHTML=rowsHtml([['Persistent storage',persisted?'כן':'לא / לא הובטח'],['Usage',usage?fmt(usage/1048576,2)+' MB':'—'],['Quota',quota?fmt(quota/1048576,1)+' MB':'—'],['Usage / quota',quota?pct(usage/quota,2):'—']]);}catch{$('storageInfo').innerHTML=rowsHtml([['Storage API','לא זמין']]);}}
async function requestPersistentStorage(){try{const ok=await navigator.storage?.persist?.();await refreshStorageUi();$('saveStatus').className=ok?'saveOk':'saveWarn';$('saveStatus').textContent=ok?'✓ אחסון מתמשך אושר':'⚠ הדפדפן לא הבטיח אחסון מתמשך; Autosave עדיין פעיל';}catch(err){$('saveStatus').className='saveWarn';$('saveStatus').textContent='⚠ בקשת אחסון מתמשך נכשלה: '+err.message;}}
async function birthRecordFor(agentId){if(!db||!runMeta.runId)return null;const tx=db.transaction('events'),idx=tx.objectStore('events').index('runChild');return await reqPromise(idx.get([runMeta.runId,Number(agentId)]));}
async function reconstructAncestry(){const root=selectedAgent();if(!root){$('ancestryTable').innerHTML='<tr><td colspan="6">בחר Somik.</td></tr>';return;}const maxDepth=Math.max(1,Math.min(30,Number($('ancestryDepth').value)||8)),seen=new Set(),queue=[{id:root.id,depth:0}],rows=[];while(queue.length&&rows.length<1000){const cur=queue.shift();if(seen.has(cur.id)||cur.depth>maxDepth)continue;seen.add(cur.id);let rec=world.lineageRecent.get(cur.id)||null;if(!rec){const ev=await birthRecordFor(cur.id);if(ev)rec={id:ev.child,parentA:ev.parentA,parentB:ev.parentB,generation:ev.generation,genomeHash:ev.genomeHash};}if(!rec&&cur.id===root.id)rec={id:root.id,parentA:root.parentA,parentB:root.parentB,generation:root.generation,genomeHash:E.genomeHash(root.genome)};if(!rec){rows.push({depth:cur.depth,id:cur.id,generation:'—',parentA:'—',parentB:'—',genomeHash:'archive unavailable'});continue;}rows.push({depth:cur.depth,...rec});if(cur.depth<maxDepth){if(rec.parentA)queue.push({id:rec.parentA,depth:cur.depth+1});if(rec.parentB)queue.push({id:rec.parentB,depth:cur.depth+1});}}$('ancestryTable').innerHTML=rows.map(r=>`<tr><td>${r.depth}</td><td>${r.id}</td><td>${r.generation??'—'}</td><td>${r.parentA||'—'}</td><td>${r.parentB||'—'}</td><td class="mono">${r.genomeHash||'—'}</td></tr>`).join('')||'<tr><td colspan="6">אין נתונים.</td></tr>';}

function newWorld(seed=1){importedEvents=[];seed=Math.max(1,Number(seed)>>>0);world=new E.World({seed});runMeta={runId:makeRunId(seed),createdAt:nowIso(),lastSaveAt:'',lastSaveTick:-1,eventSeq:0};selectedId=null;running=true;lastAutosaveWall=Date.now();lastAutosaveTick=0;$('seedInput').value=seed;updateRunIdentity();updatePauseUi();fullRefresh();saveNow('new-run');}
function updateRunIdentity(){$('runIdLabel').textContent=runMeta.runId||'—';$('protocolBadge').textContent=`${E.PROTOCOL_ID} · ${E.PROTOCOL_HASH}`;$('identityRows').innerHTML=rowsHtml([['Run ID',runMeta.runId],['Seed',world?.seed],['Protocol',E.PROTOCOL_ID],['Protocol hash',E.PROTOCOL_HASH],['Engine hash',E.ENGINE_HASH],['Variant hash',world?.protocolVariantHash],['Founder genome',world?.ancestorHash]]);}
function updatePauseUi(){$('pauseBtn').textContent=running?'⏸ עצור':'▶ הפעל';$('runStatus').textContent=world?.extinct?'נכחד':world?.technicalFailure?'תקלה':running?'רץ':'עצור';$('runStatus').className='statusPill '+(running?'run':'stop');}

function rowsHtml(rows){return rows.map(([a,b,cls])=>`<div class="row"><span>${a}</span><b class="${cls||''}">${b??'—'}</b></div>`).join('');}
function selectedAgent(){return world?.agents.find(a=>a.id===selectedId)||null;}
function currentGenome(){return brainMode==='founder'?world?.ancestorGenome:selectedAgent()?.genome||world?.ancestorGenome;}

function updateMetrics(){if(!world)return;const m=world.metrics();lastMetrics=m;$('kPop').textContent=fmt(m.population,0);$('kGen').textContent=fmt(m.medianGeneration,1);$('kBirth').textContent=fmt(m.births,0);$('kTick').textContent=fmt(m.tick,0);$('kFitness').textContent=fmt(m.reproductionRatePer1000MatureTicks,3);$('kGenDist').textContent=fmt(m.meanGeneticDistance,4);$('stateHashLabel').textContent=world.stateHash();
  $('primaryRows').innerHTML=rowsHtml([['צאצאים עד גיל קבוע',fmt(m.meanOffspringFixedAge,3)],['התרבו עד גיל קבוע',pct(m.reproducedFixedAgeFraction)],['LRS של חיים שהסתיימו',fmt(m.completedLRS,3)],['התרבו לפחות פעם אחת',pct(m.completedReproducedFraction)],['רבייה / 1000 mature-ticks',fmt(m.reproductionRatePer1000MatureTicks,4)],['הכחדה',m.extinct?'כן':'לא']]);
  $('secondaryRows').innerHTML=rowsHtml([['אנרגיה ממוצעת',fmt(m.meanEnergy,2)],['בריאות ממוצעת',fmt(m.meanHealth,3)],['גיל ממוצע',fmt(m.meanAge,1)],['לידות / מוות',`${fmt(m.births,0)} / ${fmt(m.deaths,0)}`],['משאבים חופשיים',fmt(m.resources,0)],['גופות',fmt(m.corpses,0)]]);
  $('exploreRows').innerHTML=rowsHtml([['מרחק גנטי מהאב',fmt(m.meanGeneticDistance,5)],['מגוון גנטי',fmt(m.geneticDiversity,5)],['Genomes ייחודיים במדגם',pct(m.uniqueGenomeFraction)],['Top genome share',pct(m.topGenomeShare)],['Brain complexity',fmt(m.brainComplexity,2)],['Novelty',fmt(m.phenotypeNovelty,4)],['Clusters תצפיתיים',fmt(m.observerClusters,0)]]);
  updateSelectedSide();updateEvolutionUi();updateEcologyUi();updateArchiveSimple();
}
function signedSensorHtml(label,value){const v=Number(value)||0,p=Math.max(0,Math.min(100,(v+1)*50));return `<div class="sensorItem"><div class="sensorLine"><span>${label}</span><b>${v.toFixed(3)}</b></div><div class="sensorBar signed"><i style="width:${p}%"></i></div></div>`;}
function unitSensorHtml(label,value){const v=Math.max(0,Math.min(1,Number(value)||0)),p=v*100;return `<div class="sensorItem"><div class="sensorLine"><span>${label}</span><b>${v.toFixed(3)}</b></div><div class="sensorBar"><i style="width:${p}%"></i></div></div>`;}
function updateClassicInspector(a){
  const badge=$('selectedQuickBadge'),sensors=$('selectedSensors'),actions=$('selectedActions');
  if(!a){if(badge)badge.textContent='לחץ על Somik';if(sensors)sensors.innerHTML='<div class="small">בחר Somik.</div>';if(actions)actions.innerHTML='<div class="small">בחר Somik.</div>';drawBrainMini();return;}
  if(badge)badge.textContent='#'+a.id;
  if(sensors){const inp=a.lastInputs||{};let html=signedSensorHtml('אנרגיה',inp.energy)+signedSensorHtml('בריאות',inp.health)+signedSensorHtml('מגע',inp.touch)+signedSensorHtml('שדה כימי',inp.chemical);a.genome.sensors.forEach((s,i)=>{html+=signedSensorHtml(`Ray ${i+1} · ${Math.round(s.range)}px`,inp['ray:'+s.id]);});sensors.innerHTML=html;}
  if(actions){const o=a.outputs||{};actions.innerHTML=rowsHtml([['מנוע שמאל',fmt(o.left_motor,3)],['מנוע ימין',fmt(o.right_motor,3)],['לסת',fmt(o.jaw,3)],['אחיזה',fmt(o.grip,3)],['פליטה כימית',fmt(o.chemical_emit,3)]]);}
  drawBrainMini();
}
function updateSelectedSide(){const a=selectedAgent();if(!a){$('selectedSide').textContent='לא נבחר Somik.';$('selectedLabel').textContent='לחץ על Somik לבחירה';updateClassicInspector(null);return;}const g=a.genome,p=a.pheno;$('selectedLabel').textContent=`Somik #${a.id} · דור ${a.generation} · genome ${E.genomeHash(g)}`;$('selectedSide').innerHTML=rowsHtml([['ID',a.id],['דור',a.generation],['גיל',fmt(a.age,0)],['אנרגיה',`${fmt(a.energy,1)} / ${fmt(p.energyCapacity,1)}`],['בריאות',fmt(a.health,3)],['צאצאים',a.offspring],['הורים',`${a.parentA||'—'} / ${a.parentB||'—'}`],['Genome',E.genomeHash(g),'mono'],['מרחק מהאב',fmt(E.genomeDistance(g,world.ancestorGenome),5)],['גודל גוף',fmt(p.radius,2)],['Hidden / Connections',`${g.hidden.length} / ${g.connections.filter(c=>c.enabled).length}`]]);updateClassicInspector(a);}

let trailRun='',trails=new Map();
function drawWorld(){if(!world||!renderEnabled)return;const c=$('world'),ctx=c.getContext('2d'),W=c.width,H=c.height,sx=W/E.Protocol.world.width,sy=H/E.Protocol.world.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b4d42';ctx.fillRect(0,0,W,H);
  // faint toroidal reference grid — observer only
  ctx.strokeStyle='rgba(255,255,255,.035)';ctx.lineWidth=1;for(let x=100;x<E.Protocol.world.width;x+=100){ctx.beginPath();ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,H);ctx.stroke();}for(let y=100;y<E.Protocol.world.height;y+=100){ctx.beginPath();ctx.moveTo(0,y*sy);ctx.lineTo(W,y*sy);ctx.stroke();}
  if($('layerResources').checked)for(const r of world.resources){ctx.fillStyle=COLORS[r.material]||'#fff';ctx.beginPath();ctx.arc(r.x*sx,r.y*sy,Math.max(1.4,E.Protocol.resources.resourceRadius*sx),0,Math.PI*2);ctx.fill();}
  for(const o of world.objects){ctx.fillStyle=COLORS.object;ctx.strokeStyle='#64748b';ctx.lineWidth=1;ctx.beginPath();ctx.arc(o.x*sx,o.y*sy,o.radius*sx,0,Math.PI*2);ctx.fill();ctx.stroke();}
  if($('layerResources').checked)for(const co of world.corpses){ctx.fillStyle=COLORS.corpse;ctx.beginPath();ctx.arc(co.x*sx,co.y*sy,co.radius*sx,0,Math.PI*2);ctx.fill();}
  if(trailRun!==runMeta.runId){trails.clear();trailRun=runMeta.runId;}
  const alive=new Set(world.agents.map(a=>a.id));for(const id of trails.keys())if(!alive.has(id))trails.delete(id);
  if($('layerTrails').checked){ctx.strokeStyle='rgba(186,230,253,.30)';ctx.lineWidth=1;for(const a of world.agents){const points=trails.get(a.id)||[];if(points.at(-1)?.tick!==world.tick)points.push({x:a.x,y:a.y,tick:world.tick});if(points.length>60)points.shift();trails.set(a.id,points);ctx.beginPath();points.forEach((p,i)=>{const prev=points[i-1];if(!prev||Math.abs(prev.x-p.x)>E.Protocol.world.width/2||Math.abs(prev.y-p.y)>E.Protocol.world.height/2)ctx.moveTo(p.x*sx,p.y*sy);else ctx.lineTo(p.x*sx,p.y*sy);});ctx.stroke();}}
  if($('layerInteractions').checked){const pool=new Map([...world.objects,...world.resources,...world.corpses].map(e=>[e.kind+':'+e.id,e]));ctx.strokeStyle='#f9a8d4';for(const a of world.agents){const e=a.holding&&pool.get(a.holding.kind+':'+a.holding.id);if(e&&Math.abs(a.x-e.x)<E.Protocol.world.width/2&&Math.abs(a.y-e.y)<E.Protocol.world.height/2){ctx.beginPath();ctx.moveTo(a.x*sx,a.y*sy);ctx.lineTo(e.x*sx,e.y*sy);ctx.stroke();}}}
  const sel=selectedAgent();for(const a of world.agents){const r=Math.max(2,a.pheno.radius*sx),x=a.x*sx,y=a.y*sy;if($('layerInteractions').checked&&a.lastEmit>0.12){ctx.strokeStyle=`rgba(216,180,254,${Math.min(.28,a.lastEmit*.3)})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,Math.min(90,28+a.lastEmit*70)*sx,0,Math.PI*2);ctx.stroke();}ctx.fillStyle=COLORS.agent;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#082f49';ctx.lineWidth=1;ctx.stroke();ctx.strokeStyle='#e0f2fe';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a.dir)*r*1.7,y+Math.sin(a.dir)*r*1.7);ctx.stroke();if(a.id===selectedId){ctx.strokeStyle='#fff';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(x,y,r+4,0,Math.PI*2);ctx.stroke();}}
  if(sel&&$('raysCheck').checked){ctx.save();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=1;for(const s of sel.genome.sensors){const ang=sel.dir+s.angle;ctx.beginPath();ctx.moveTo(sel.x*sx,sel.y*sy);ctx.lineTo((sel.x+Math.cos(ang)*s.range)*sx,(sel.y+Math.sin(ang)*s.range)*sy);ctx.stroke();}ctx.restore();}
}
function worldClick(ev){const rect=$('world').getBoundingClientRect(),x=(ev.clientX-rect.left)/rect.width*E.Protocol.world.width,y=(ev.clientY-rect.top)/rect.height*E.Protocol.world.height;let best=null,bd=Infinity;for(const a of world.agents){const d=E.helpers.dist2(x,y,a.x,a.y);if(d<bd){bd=d;best=a;}}if(best&&Math.sqrt(bd)<35){selectedId=best.id;brainMode='selected';fullRefresh();}}

function canvasFit(c){const dpr=Math.min(2,devicePixelRatio||1),rect=c.getBoundingClientRect(),w=Math.max(320,Math.floor(rect.width*dpr)),h=Math.max(180,Math.floor(rect.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h;}return{ctx:c.getContext('2d'),w,h,dpr};}
function chart(canvas,series){const {ctx,w,h}=canvasFit(canvas);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d1626';ctx.fillRect(0,0,w,h);const pad=34,pts=world?.archive?.flattened(1800)||[];if(pts.length<2){ctx.fillStyle='#94a3b8';ctx.font='12px Arial';ctx.fillText('ממתין לנתונים…',pad,30);return;}const xs=pts.map(p=>p.tick);let vals=[];for(const s of series)for(const p of pts){const v=s.get(p);if(Number.isFinite(v))vals.push(v);}if(!vals.length)return;let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1;}const x0=Math.min(...xs),x1=Math.max(...xs)||1;ctx.strokeStyle='#334155';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad,8);ctx.lineTo(pad,h-pad);ctx.lineTo(w-8,h-pad);ctx.stroke();ctx.fillStyle='#94a3b8';ctx.font=`${11*(devicePixelRatio||1)}px Arial`;ctx.fillText(fmt(max,2),3,15);ctx.fillText(fmt(min,2),3,h-pad);for(const s of series){ctx.strokeStyle=s.color;ctx.lineWidth=1.7*(devicePixelRatio||1);ctx.beginPath();let started=false;for(const p of pts){const v=s.get(p);if(!Number.isFinite(v))continue;const x=pad+(p.tick-x0)/(x1-x0||1)*(w-pad-10),y=8+(max-v)/(max-min)*(h-pad-16);if(!started){ctx.moveTo(x,y);started=true;}else ctx.lineTo(x,y);}ctx.stroke();}let lx=pad+5;for(const s of series){ctx.fillStyle=s.color;ctx.fillRect(lx,10,9,9);ctx.fillStyle='#cbd5e1';ctx.fillText(s.name,lx+13,19);lx+=ctx.measureText(s.name).width+36;}}
function updateCharts(){if(!world)return;chart($('chartPop'),[{name:'Population',color:'#38bdf8',get:p=>p.population},{name:'Median Gen',color:'#fbbf24',get:p=>p.medianGeneration}]);chart($('chartGenetic'),[{name:'Distance',color:'#f472b6',get:p=>p.meanGeneticDistance},{name:'Diversity',color:'#a78bfa',get:p=>p.geneticDiversity}]);chart($('chartFitness'),[{name:'Repro rate',color:'#4ade80',get:p=>p.reproductionRatePer1000MatureTicks},{name:'LRS',color:'#fbbf24',get:p=>p.completedLRS}]);chart($('chartComplex'),[{name:'Brain',color:'#38bdf8',get:p=>p.brainComplexity},{name:'Novelty',color:'#f472b6',get:p=>p.phenotypeNovelty},{name:'Clusters',color:'#fbbf24',get:p=>p.observerClusters}]);chart($('chartMorph'),[{name:'Radius',color:'#38bdf8',get:p=>p.phenotype?.radius},{name:'Metabolism',color:'#fb7185',get:p=>p.phenotype?.baseMet},{name:'Motor power',color:'#4ade80',get:p=>p.traits?.motorPower}]);chart($('chartMaterials'),[{name:'Primary',color:COLORS.primary,get:p=>p.materials?.primary},{name:'Waste',color:COLORS.waste,get:p=>p.materials?.waste},{name:'Tissue',color:COLORS.tissue,get:p=>p.materials?.tissue}]);}

function updateEvolutionUi(){const m=lastMetrics;if(!m)return;const ms=m.mutationStats||{};$('mutationSummary').innerHTML=rowsHtml([['לידות עם mutation',fmt(ms.birthsWithMutations,0)],['שינויים גנטיים',fmt(ms.totalChanges,0)],['Trait',fmt(ms.byType?.trait,0)],['Sensor',fmt(ms.byType?.sensor,0)],['Weight',fmt(ms.byType?.weight,0)],['Bias',fmt(ms.byType?.bias,0)],['Structural',fmt(ms.byType?.structure,0)],['Mutation rate ממוצע',fmt(m.traits.mutationRate,5)],['Structural rate ממוצע',fmt(m.traits.structuralRate,5)]]);$('brainPopulation').innerHTML=rowsHtml([['Ray sensors',fmt(m.avgSensors,2)],['Hidden neurons',fmt(m.avgHidden,2)],['Connections',fmt(m.avgConnections,2)],['Brain complexity',fmt(m.brainComplexity,2)],['Unique genome fraction',pct(m.uniqueGenomeFraction)],['Top genome share',pct(m.topGenomeShare)]]);$('traitSummary').innerHTML=rowsHtml([['רדיוס',fmt(m.phenotype.radius,3)],['מסה',fmt(m.phenotype.mass,2)],['קיבולת אנרגיה',fmt(m.phenotype.energyCapacity,2)],['מטבוליזם בסיסי',fmt(m.phenotype.baseMet,5)],['מהירות פיזיקלית',fmt(m.phenotype.maxSpeed,3)],['בגרות',fmt(m.phenotype.maturity,1)],['שריון',fmt(m.traits.armor,3)],['תיקון',fmt(m.traits.repair,3)],['Digest primary',fmt(m.traits.digestPrimary,3)],['Digest waste',fmt(m.traits.digestWaste,3)],['Digest tissue',fmt(m.traits.digestTissue,3)]]);
  const gmap=new Map();for(const a of world.agents){const h=E.genomeHash(a.genome),x=gmap.get(h)||{n:0,g:0};x.n++;x.g+=a.generation;gmap.set(h,x);}const arr=[...gmap].sort((a,b)=>b[1].n-a[1].n).slice(0,20);$('genomeTable').innerHTML=arr.map(([h,x])=>`<tr><td class="mono">${h}</td><td>${x.n}</td><td>${pct(x.n/Math.max(1,world.agents.length))}</td><td>${fmt(x.g/x.n,1)}</td></tr>`).join('');
  const ev=world.recentEvents.filter(e=>e.type==='birth'&&e.mutations?.length).slice(-20).reverse();$('mutationEvents').innerHTML=ev.length?ev.map(e=>`<div class="event mut"><div class="t">tick ${fmt(e.tick,0)} · child ${e.child} · gen ${e.generation}</div><b>${e.mutations.length} שינויים</b> — ${e.mutations.slice(0,4).map(x=>x.action||x.type+':'+x.target).join(', ')}</div>`).join(''):'<div class="small">עדיין אין אירועי mutation.</div>';
}

function brainNodes(g){return{inputs:['energy','health','touch','chemical',...g.sensors.map(s=>'ray:'+s.id)],hidden:g.hidden.map(h=>h.id),outputs:['act:left_motor','act:right_motor','act:jaw','act:grip','act:chemical_emit']};}
function drawBrainMini(){
  const c=$('brainMiniCanvas');if(!c||!world)return;const {ctx,w,h}=canvasFit(c),a=selectedAgent();ctx.clearRect(0,0,w,h);ctx.fillStyle='#101827';ctx.fillRect(0,0,w,h);
  if(!a){ctx.fillStyle='#94a3b8';ctx.font=`${13*(devicePixelRatio||1)}px Arial`;ctx.textAlign='center';ctx.fillText('בחר Somik כדי לראות את המוח',w/2,h/2);ctx.textAlign='start';return;}
  const g=a.genome,nodes=brainNodes(g),pad=24*(devicePixelRatio||1),pos=new Map();function place(list,x){list.forEach((id,i)=>pos.set(id,{x,y:pad+(i+1)*(h-2*pad)/(list.length+1)}));}
  place(nodes.inputs,pad+13*(devicePixelRatio||1));place(nodes.hidden,w/2);place(nodes.outputs,w-pad-13*(devicePixelRatio||1));const maxW=Math.max(.1,...g.connections.filter(x=>x.enabled).map(x=>Math.abs(x.weight)));
  for(const cn of g.connections){if(!cn.enabled)continue;const p1=pos.get(cn.from),p2=pos.get(cn.to);if(!p1||!p2)continue;ctx.strokeStyle=cn.weight>=0?'rgba(56,189,248,.42)':'rgba(244,114,182,.42)';ctx.lineWidth=(.35+1.5*Math.abs(cn.weight)/maxW)*(devicePixelRatio||1);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();}
  for(const [id,p] of pos){let act=0;if(id.startsWith('act:'))act=a.outputs?.[id.slice(4)]||0;else if(id.startsWith('ray:')||['energy','health','touch','chemical'].includes(id))act=a.lastInputs?.[id]||0;else act=a.hiddenState?.[id]||0;const rr=(id.startsWith('ray:')||['energy','health','touch','chemical'].includes(id)?4.5:6)*(devicePixelRatio||1);ctx.fillStyle=act>=0?`rgba(56,189,248,${.30+.60*Math.min(1,Math.abs(act))})`:`rgba(244,114,182,${.30+.60*Math.min(1,Math.abs(act))})`;ctx.strokeStyle='#e2e8f0';ctx.lineWidth=.7*(devicePixelRatio||1);ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill();ctx.stroke();}
}
function drawBrain(){if(!world)return;const g=currentGenome();if(!g)return;const c=$('brainCanvas'),{ctx,w,h}=canvasFit(c),nodes=brainNodes(g),pad=48;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d1626';ctx.fillRect(0,0,w,h);const pos=new Map();function place(list,x){list.forEach((id,i)=>pos.set(id,{x,y:pad+(i+1)*(h-2*pad)/(list.length+1)}));}place(nodes.inputs,pad+30);place(nodes.hidden,w/2);place(nodes.outputs,w-pad-30);const maxW=Math.max(.1,...g.connections.map(c=>Math.abs(c.weight)));for(const cn of g.connections){if(!cn.enabled)continue;const a=pos.get(cn.from),b=pos.get(cn.to);if(!a||!b)continue;ctx.strokeStyle=cn.weight>=0?'rgba(56,189,248,.65)':'rgba(244,114,182,.65)';ctx.lineWidth=(.5+3*Math.abs(cn.weight)/maxW)*(devicePixelRatio||1);ctx.beginPath();ctx.moveTo(a.x,a.y);const mx=(a.x+b.x)/2;ctx.bezierCurveTo(mx,a.y,mx,b.y,b.x,b.y);ctx.stroke();}
  const live=brainMode==='selected'?selectedAgent():null;for(const [id,p] of pos){let act=0;if(live){if(id.startsWith('act:'))act=live.outputs[id.slice(4)]||0;else if(id.startsWith('ray:')||['energy','health','touch','chemical'].includes(id))act=live.lastInputs?.[id]||0;else act=live.hiddenState?.[id]||0;}const rr=id.startsWith('ray:')||['energy','health','touch','chemical'].includes(id)?7:id.startsWith('act:')?9:9;ctx.fillStyle=act>=0?`rgba(56,189,248,${.25+.65*Math.min(1,Math.abs(act))})`:`rgba(244,114,182,${.25+.65*Math.min(1,Math.abs(act))})`;ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,rr*(devicePixelRatio||1),0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#cbd5e1';ctx.font=`${10*(devicePixelRatio||1)}px Arial`;ctx.textAlign=id.startsWith('act:')?'right':id.startsWith('ray:')||['energy','health','touch','chemical'].includes(id)?'left':'center';const label=id.replace('act:','');ctx.fillText(label,p.x+(ctx.textAlign==='left'?12:ctx.textAlign==='right'?-12:0)*(devicePixelRatio||1),p.y-11*(devicePixelRatio||1));}ctx.textAlign='start';updateBrainDetails();}
function updateBrainDetails(){if(!world)return;const g=currentGenome(),a=selectedAgent(),found=world.ancestorGenome;if(!g)return;const enabled=g.connections.filter(c=>c.enabled),gd=E.genomeDistance(g,found);$('brainDetails').innerHTML=rowsHtml([['מצב',brainMode==='founder'?'אב קדמון':a?`Somik #${a.id}`:'אב קדמון'],['Genome',E.genomeHash(g),'mono'],['מרחק מהאב',fmt(gd,6)],['Sensors',g.sensors.length],['Hidden',g.hidden.length],['Connections enabled',enabled.length],['Mutation rate',fmt(g.traits.mutationRate,6)],['Structural rate',fmt(g.traits.structuralRate,6)]]);const fm=new Map(found.connections.map(c=>[c.id,c]));const changed=enabled.map(c=>({c,d:c.weight-(fm.get(c.id)?.weight||0),exists:fm.has(c.id)})).filter(x=>!x.exists||Math.abs(x.d)>1e-6).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d)).slice(0,120);$('connectionTable').innerHTML=changed.map(x=>`<tr><td class="mono">${x.c.id}</td><td>${x.c.from}</td><td>${x.c.to}</td><td>${fmt(x.c.weight,4)}</td><td>${x.exists?fmt(x.d,4):'חדש'}</td></tr>`).join('');$('connectionSelect').innerHTML=enabled.slice().sort((a,b)=>Math.abs(b.weight)-Math.abs(a.weight)).map(c=>`<option value="${c.id}">${c.id}: ${c.from} → ${c.to} (${fmt(c.weight,3)})</option>`).join('');}

function drawLineage(){const c=$('lineageCanvas'),{ctx,w,h}=canvasFit(c);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d1626';ctx.fillRect(0,0,w,h);const root=selectedAgent();if(!root){ctx.fillStyle='#94a3b8';ctx.fillText('בחר Somik',20,30);return;}const byId=world.lineageRecent;const levels=[[root]],seen=new Set([root.id]);for(let d=1;d<6;d++){const prev=levels[d-1],cur=[];for(const x of prev){const rec=x.kind==='agent'?x:byId.get(x.id);for(const pid of [rec?.parentA,rec?.parentB])if(pid&&!seen.has(pid)&&byId.has(pid)){seen.add(pid);cur.push(byId.get(pid));}}if(!cur.length)break;levels.push(cur);}const pos=new Map();for(let d=0;d<levels.length;d++){const list=levels[d];for(let i=0;i<list.length;i++){const x=w/2+(i-(list.length-1)/2)*Math.min(90,w/Math.max(2,list.length+1)),y=35+d*(h-60)/Math.max(1,levels.length-1);pos.set(list[i].id,{x,y});}}ctx.strokeStyle='#64748b';for(let d=0;d<levels.length-1;d++)for(const x of levels[d]){const rec=x.kind==='agent'?x:byId.get(x.id),p=pos.get(x.id);for(const pid of [rec?.parentA,rec?.parentB])if(pos.has(pid)){const q=pos.get(pid);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}for(const [id,p] of pos){ctx.fillStyle=id===root.id?'#fff':'#38bdf8';ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#cbd5e1';ctx.font='10px Arial';ctx.fillText('#'+id,p.x+8,p.y+3);}}
function updateLineages(){if(!world)return;drawLineage();const rows=[];const bins=Object.keys(world.cohortStats).map(Number).sort((a,b)=>a-b).slice(-8);for(const bin of bins){const c=world.cohortStats[bin],birthTotal=Object.values(c.birthAncestry||{}).reduce((a,b)=>a+b,0),expTotal=Object.values(c.eligibleExposure||{}).reduce((a,b)=>a+b,0);const keys=new Set([...Object.keys(c.birthAncestry||{}),...Object.keys(c.eligibleExposure||{})]);for(const k of keys){const bs=(c.birthAncestry?.[k]||0)/Math.max(1e-9,birthTotal),es=(c.eligibleExposure?.[k]||0)/Math.max(1e-9,expTotal);if(es<0.01)continue;rows.push({bin,k,bs,es,rf:bs/es});}}rows.sort((a,b)=>b.bin-a.bin||b.rf-a.rf);$('lineageFitnessTable').innerHTML=rows.slice(0,80).map(x=>`<tr><td>${x.bin}–${x.bin+49}</td><td>${x.k}</td><td>${pct(x.bs,2)}</td><td>${pct(x.es,2)}</td><td>${fmt(x.rf,3)}</td></tr>`).join('');const mass={};for(const a of world.agents)for(const[k,v]of Object.entries(a.ancestry||{}))mass[k]=(mass[k]||0)+v;const total=world.agents.length||1;$('founderAncestry').innerHTML=Object.entries(mass).sort((a,b)=>b[1]-a[1]).slice(0,15).map(([k,v])=>`<div class="row"><span>Founder ${k}</span><b>${pct(v/total,2)}</b></div>`).join('')||'<div class="small">—</div>';const ev=world.recentEvents.filter(e=>['birth','death','checkpoint','technical_failure'].includes(e.type)).slice(-40).reverse();$('eventLog').innerHTML=ev.map(e=>`<div class="event ${e.type}"><div class="t">tick ${fmt(e.tick,0)}</div><b>${e.type}</b> ${e.type==='birth'?`child ${e.child} · parents ${e.parentA}/${e.parentB||'—'} · gen ${e.generation}${e.mutations?.length?` · ${e.mutations.length} mutations`:''}`:e.type==='death'?`agent ${e.agent} · gen ${e.generation} · offspring ${e.offspring}`:e.type==='checkpoint'?`generation ${e.generation}`:(e.message||'')}</div>`).join('');}

function updateEcologyUi(){const m=lastMetrics;if(!m)return;$('materialsRows').innerHTML=rowsHtml([['Primary',fmt(m.materials.primary,2)],['Waste',fmt(m.materials.waste,2)],['Tissue',fmt(m.materials.tissue,2)],['Corpse biomass',fmt(m.corpseBiomass,2)],['Loose resources',fmt(m.resources,0)],['Objects',fmt(m.objects,0)]]);const e=m.ecology;$('ecologyRows').innerHTML=rowsHtml([['Primary consumed',fmt(e.consumedPrimary,2)],['Waste consumed',fmt(e.consumedWaste,2)],['Tissue consumed',fmt(e.consumedTissue,2)],['Bites',fmt(e.bites,0)],['Predation damage',fmt(e.predationDamage,4)],['Grips',fmt(e.grips,0)],['Object carry ticks',fmt(e.objectCarryTicks,0)],['Chemical emission',fmt(e.chemicalEmission,2)],['Waste produced',fmt(e.wasteProduced,2)],['Corpses created',fmt(e.corpsesCreated,0)]]);const b=m.behavior;$('behaviorRows').innerHTML=rowsHtml([['Distance / 1000 age',fmt(b.distancePer1000Age,2)],['Primary / 1000 age',fmt(b.primaryPer1000Age,3)],['Waste / 1000 age',fmt(b.wastePer1000Age,3)],['Tissue / 1000 age',fmt(b.tissuePer1000Age,3)],['Grip lifetime fraction',pct(b.gripFraction,2)],['Chemical / 1000 age',fmt(b.chemicalPer1000Age,3)],['Damage given / 1000',fmt(b.damageGivenPer1000Age,5)],['Damage taken / 1000',fmt(b.damageTakenPer1000Age,5)]]);const a=selectedAgent();$('selectedEcology').innerHTML=a?rowsHtml([['מרחק חיים',fmt(a.distance,2)],['Primary eaten',fmt(a.foodPrimary,3)],['Waste eaten',fmt(a.foodWaste,3)],['Tissue eaten',fmt(a.foodTissue,3)],['Damage given',fmt(a.damageGiven,5)],['Damage taken',fmt(a.damageTaken,5)],['Grip ticks',fmt(a.gripTicks,0)],['Chemical total',fmt(a.chemicalTotal,3)],['Holding',a.holding?`${a.holding.kind} #${a.holding.id}`:'לא']]):'<div class="small">בחר Somik.</div>';drawTradeoff();}
function drawTradeoff(){const c=$('tradeoffCanvas'),{ctx,w,h}=canvasFit(c),arr=world?.agents||[];ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d1626';ctx.fillRect(0,0,w,h);if(!arr.length)return;const samp=arr.length>300?arr.filter((_,i)=>i%Math.ceil(arr.length/300)===0):arr;const pts=samp.map(a=>({x:a.pheno.baseMet,y:a.pheno.energyCapacity,r:a.pheno.radius})),xmin=Math.min(...pts.map(p=>p.x)),xmax=Math.max(...pts.map(p=>p.x)),ymin=Math.min(...pts.map(p=>p.y)),ymax=Math.max(...pts.map(p=>p.y)),pad=28;ctx.strokeStyle='#334155';ctx.beginPath();ctx.moveTo(pad,8);ctx.lineTo(pad,h-pad);ctx.lineTo(w-8,h-pad);ctx.stroke();for(const p of pts){const x=pad+(p.x-xmin)/(xmax-xmin||1)*(w-pad-10),y=8+(ymax-p.y)/(ymax-ymin||1)*(h-pad-16);ctx.fillStyle='rgba(56,189,248,.55)';ctx.beginPath();ctx.arc(x,y,Math.max(2,p.r*.5),0,Math.PI*2);ctx.fill();}}

function updateArchiveSimple(){if(!world)return;const cps=Object.values(world.checkpoints||{}).sort((a,b)=>a.generation-b.generation);$('checkpointTable').innerHTML=cps.map(c=>`<tr><td>${c.generation}</td><td>${fmt(c.tick,0)}</td><td>${c.genomes.length}</td><td>${fmt(c.metrics.population,0)}</td><td>${fmt(c.metrics.meanGeneticDistance,5)}</td></tr>`).join('');const levels=world.archive?.levels||[];$('archiveRows').innerHTML=rowsHtml([['Base stride',world.archive?.baseStride],['רמות',levels.length],['Samples',levels.reduce((s,x)=>s+x.length,0)],...levels.map((x,i)=>[`Level ${i}`,x.length])]);$('autosaveInfo').innerHTML=rowsHtml([['שמירה אחרונה',runMeta.lastSaveAt?new Date(runMeta.lastSaveAt).toLocaleString('he-IL'):'טרם נשמר'],['Tick אחרון',fmt(runMeta.lastSaveTick,0)],['Rolling snapshots',ROLLING_SAVES],['Autosave wall-time',AUTOSAVE_MS/1000+' sec'],['Autosave tick interval',fmt(AUTOSAVE_TICKS,0)]]);}
async function refreshArchiveUi(){if(!db||!world)return;try{const runs=await listRuns();$('runsTable').innerHTML=runs.map(r=>`<tr><td class="mono">${r.runId}</td><td>${r.seed}</td><td>${fmt(r.tick,0)}</td><td>${new Date(r.savedAt).toLocaleString('he-IL')}</td><td><button onclick="loadSnapshotByKey('${r.key.replaceAll("'","\'")}')">טען</button></td></tr>`).join('');const cnt=await countEvents();$('eventArchiveRows').innerHTML=rowsHtml([['אירועים שמורים ב־IndexedDB',fmt(cnt,0)],['Event sequence',fmt(runMeta.eventSeq,0)],['Persistent types','birth / death / checkpoint / failure'],['Birth mutation detail','כן']]);await refreshStorageUi();}catch(err){console.error('Archive refresh failed',err);}}

function checkpointGenome(){const cps=Object.values(world.checkpoints||{}).sort((a,b)=>b.generation-a.generation);return cps[0]?.genomes?.[0]||null;}
function labWorker(){const url=new URL('research-engine.js',location.href).href,engineBootstrap=globalThis.__SOMIK_ENGINE_SOURCE||`importScripts(${JSON.stringify(url)});`;const code=`${engineBootstrap}\nconst E=SomikResearch;onmessage=e=>{const m=e.data;try{let r;if(m.cmd==='selftest'){r=E.selfTest();}else if(m.cmd==='assayPair'){const a=E.runAssay(m.ancestor,m.seed,m.opts),b=E.runAssay(m.genome,m.seed,m.opts);r={ancestor:a,evolved:b,ratio:a.reproRate>0?b.reproRate/a.reproRate:null};}else if(m.cmd==='common'){r=E.commonGarden([m.genome],m.ancestor,m.seeds,m.opts);}else if(m.cmd==='neighborhood'){r=E.mutationalNeighborhood(m.genome,m.seed,m.n,m.opts);}else if(m.cmd==='control'){const w=new E.World({seed:m.seed,mutationEnabled:false,reproductionMode:'sexual',objectsEnabled:true,chemicalEnabled:true});for(let i=0;i<m.ticks&&!w.extinct&&!w.technicalFailure;i++)w.step();r={metrics:w.metrics(),stateHash:w.stateHash(),uniqueGenomes:new Set(w.agents.map(a=>E.genomeHash(a.genome))).size};}else if(m.cmd==='multiseed'){const rows=[];for(let i=0;i<m.n;i++){const seed=m.base+i;const w=new E.World({seed});for(let t=0;t<m.ticks&&!w.extinct&&!w.technicalFailure;t++)w.step();rows.push({seed,...w.metrics(),stateHash:w.stateHash()});}r=rows;}else if(m.cmd==='variant'){const o=m.options||{},w=new E.World({seed:m.seed,mutationEnabled:o.mutationEnabled!==false,reproductionMode:o.reproductionMode||'sexual',objectsEnabled:o.objectsEnabled!==false,chemicalEnabled:o.chemicalEnabled!==false,memoryEnabled:o.memoryEnabled!==false});for(let t=0;t<m.ticks&&!w.extinct&&!w.technicalFailure;t++)w.step();r={treatment:w.treatment,metrics:w.metrics(),stateHash:w.stateHash(),protocolVariantHash:w.protocolVariantHash};}else if(m.cmd==='knockout'){const ko=E.knockoutGenome(m.genome,m.conn);const base=E.runAssay(m.genome,m.seed,m.opts),knock=E.runAssay(ko,m.seed,m.opts);r={base,knockout:knock,ratio:base.reproRate>0?knock.reproRate/base.reproRate:null};}postMessage({ok:true,r});}catch(err){postMessage({ok:false,error:String(err.stack||err)});}}`;const blobUrl=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));const worker=new Worker(blobUrl);worker.sourceUrl=blobUrl;return worker;}
const activeWorkers=new Map();
function runWorker(msg,outId,format=x=>JSON.stringify(x,null,2)){
  const out=$(outId),previous=activeWorkers.get(outId);if(previous){previous.terminate();URL.revokeObjectURL(previous.sourceUrl);}
  out.textContent='מריץ ניסוי…';let w;
  const finish=()=>{w?.terminate();if(w)URL.revokeObjectURL(w.sourceUrl);activeWorkers.delete(outId);};
  try{w=labWorker();activeWorkers.set(outId,w);
    w.onmessage=e=>{finish();out.textContent=e.data.ok?format(e.data.r):'ERROR: '+e.data.error;};
    w.onerror=e=>{finish();out.textContent='הניסוי נכשל: '+e.message;};w.postMessage(msg);
  }catch(err){finish();out.textContent='לא ניתן להריץ ניסוי: '+err.message;}
}
function assayOpts(){return{ticks:Math.max(500,Number($('assayTicks').value)||4000),founderCount:20,reproductionMode:'asexual',objectsEnabled:false,chemicalEnabled:false};}

function drawBrainAndLineage(){drawBrain();updateLineages();}
function updateProtocolUi(){$('protocolText').textContent=JSON.stringify(E.Protocol,null,2);updateRunIdentity();}
function runSelfTest(){runWorker({cmd:'selftest'},'selfTestOut',t=>(t.ok?'PASS':'FAIL')+' · '+t.results.length+' checks\n'+t.results.map(x=>`${x.ok?'✓':'✗'} ${x.name}${x.detail?' — '+x.detail:''}`).join('\n'));}

function fullRefresh(){updateMetrics();drawWorld();updateCharts();drawBrainAndLineage();updateProtocolUi();refreshArchiveUi();}
function uiRefresh(){updateMetrics();drawBrainMini();drawChartsIfVisible();if(document.getElementById('tab-brain').classList.contains('active'))drawBrain();if(document.getElementById('tab-lineages').classList.contains('active'))updateLineages();if(document.getElementById('tab-ecology').classList.contains('active'))drawTradeoff();}
function drawChartsIfVisible(){if($('tab-overview').classList.contains('active'))updateCharts();}

function loop(now){requestAnimationFrame(loop);if(!world)return;let steps=0;if(running&&!world.extinct&&!world.technicalFailure){const target=speed,budget=speed>=500?15:speed>=100?10:8,start=performance.now();while(steps<target&&performance.now()-start<budget){world.step();steps++;if(world.extinct||world.technicalFailure)break;}ticksSincePerf+=steps;if(world.extinct||world.technicalFailure){running=false;updatePauseUi();saveNow(world.extinct?'extinction':'technical-failure');}}
  if(now-lastPerfAt>1000){currentTPS=ticksSincePerf*1000/(now-lastPerfAt);ticksSincePerf=0;lastPerfAt=now;$('computeLine').textContent=`${fmt(currentTPS,0)} ticks/s · target x${speed}`;}
  if(!saveInFlight&&(Date.now()-lastAutosaveWall>AUTOSAVE_MS||world.tick-lastAutosaveTick>=AUTOSAVE_TICKS))saveNow('autosave');
  if(now-lastUiAt>500){uiRefresh();lastUiAt=now;}
  if(renderEnabled&&now-lastDrawAt>(speed>=500?250:speed>=100?100:40)){drawWorld();lastDrawAt=now;}
}

async function exportRun(full=false){
  const was=running;running=false;updatePauseUi();try{
    await saveNow('export');
    const state=JSON.parse(JSON.stringify(world.dump()));
    const data={schema:'SomikWorldResearchExport/1.1',exportedAt:nowIso(),runMeta:{...runMeta},protocol:E.Protocol,
      protocolId:E.PROTOCOL_ID,protocolHash:E.PROTOCOL_HASH,engineHash:E.ENGINE_HASH,
      stateHash:world.stateHash(),snapshotHash:E.snapshotHash(state),state,summary:world.metrics()};
    if(full)data.events=[...await getAllEvents(),...importedEvents];
    data.archiveComplete=!!db&&!importedEvents.length&&runMeta.lastSaveTick===world.tick;
    downloadJson(data,`somik-research-${runMeta.runId}-${full?'full-archive':'run'}.json`);
  }finally{running=was&&!world.extinct&&!world.technicalFailure;updatePauseUi();}
}
function downloadJson(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
async function importFile(file){
  const data=JSON.parse(await file.text()),state=data.state||data;
  if(data.snapshotHash&&E.snapshotHash(state)!==data.snapshotHash)throw new Error('Snapshot checksum mismatch');
  const loaded=E.World.load(state);
  if(data.stateHash&&loaded.stateHash()!==data.stateHash)throw new Error('Scientific state checksum mismatch');
  const entries=(data.events||[]).map(compactEvent).filter(Boolean);
  if(entries.some(e=>!Number.isSafeInteger(e.tick)||e.tick<0||e.tick>loaded.tick))throw new Error('Invalid archive event');
  const was=running;running=false;if(db&&!await saveNow('before-import')){running=was;throw new Error('Save failed; current run retained');}
  world=loaded;importedEvents=entries;runMeta={runId:makeRunId(world.seed),sourceRunId:data.runMeta?.runId||null,
    createdAt:nowIso(),lastSaveAt:'',lastSaveTick:-1,eventSeq:0,archiveOrigin:data.events?'imported-full':'snapshot-only'};
  selectedId=null;running=false;lastAutosaveWall=Date.now();lastAutosaveTick=world.tick;
  $('seedInput').value=world.seed;updatePauseUi();updateRunIdentity();fullRefresh();await saveNow('import');
}

function bind(){
  $('openV3Btn').onclick=()=>{if(globalThis.__SOMIK_V3_SOURCE){const u=URL.createObjectURL(new Blob([globalThis.__SOMIK_V3_SOURCE],{type:'text/html'}));window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000);}else window.open('v3-baseline.html','_blank','noopener');};
  $('pauseBtn').onclick=()=>{running=!running&&!world.extinct&&!world.technicalFailure;updatePauseUi();};$('speedSel').onchange=e=>speed=Number(e.target.value)||1;$('renderBtn').onclick=()=>{renderEnabled=!renderEnabled;$('renderBtn').textContent=`👁 תצוגה: ${renderEnabled?'פעילה':'חסכונית'}`;if(renderEnabled)drawWorld();};$('saveBtn').onclick=()=>saveNow('manual');$('exportBtn').onclick=()=>exportRun(false);$('exportFullBtn').onclick=()=>exportRun(true);$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{if(e.target.files[0])await importFile(e.target.files[0]);}catch(err){alert(err.message);}e.target.value='';};$('newRunBtn').onclick=async()=>{if(!confirm('לשמור את ה־Run הנוכחי וליצור Run חדש?'))return;running=false;if(db&&!await saveNow('before-new-run')){updatePauseUi();return;}newWorld(Number($('seedInput').value)||1);};$('world').addEventListener('click',worldClick);if($('openBrainTabBtn'))$('openBrainTabBtn').onclick=()=>{const b=document.querySelector('.tabBtn[data-tab="brain"]');if(b){b.click();setTimeout(()=>document.getElementById('tab-brain')?.scrollIntoView({behavior:'smooth',block:'start'}),40);}};
  document.querySelectorAll('.tabBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabBtn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabPane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active');setTimeout(()=>{uiRefresh();drawBrainAndLineage();},20);});
  $('brainSelectedBtn').onclick=()=>{brainMode='selected';drawBrain();};$('brainFounderBtn').onclick=()=>{brainMode='founder';drawBrain();};$('knockoutBtn').onclick=()=>{const g=currentGenome(),conn=$('connectionSelect').value;if(!g||!conn)return;runWorker({cmd:'knockout',genome:g,conn,seed:93001,opts:assayOpts()},'commonGardenOut');};$('commonGardenBtn').onclick=()=>{const a=selectedAgent();if(!a)return $('commonGardenOut').textContent='בחר Somik.';runWorker({cmd:'common',genome:a.genome,ancestor:world.ancestorGenome,seeds:[91001,91002,91003,91004,91005],opts:assayOpts()},'commonGardenOut',r=>`Mean ratio evolved/ancestor: ${fmt(r.meanRatio,4)}\nMean log ratio: ${fmt(r.meanLogRatio,4)}\n\n`+JSON.stringify(r.ratios,null,2));};$('ancestorReplayBtn').onclick=()=>{const a=selectedAgent();if(!a)return $('commonGardenOut').textContent='בחר Somik.';runWorker({cmd:'assayPair',genome:a.genome,ancestor:world.ancestorGenome,seed:92001,opts:assayOpts()},'commonGardenOut');};$('mutationOffBtn').onclick=()=>runWorker({cmd:'control',seed:world.seed,ticks:Math.max(500,Number($('controlTicks').value)||5000)},'mutationOffOut',r=>`Mutation-Off · same seed ${world.seed}\nUnique genomes alive: ${r.uniqueGenomes}\nState hash: ${r.stateHash}\n\n${JSON.stringify(r.metrics,null,2)}`);$('neighborhoodBtn').onclick=()=>{const a=selectedAgent();if(!a)return $('neighborhoodOut').textContent='בחר Somik.';runWorker({cmd:'neighborhood',genome:a.genome,seed:99001,n:Number($('mutantN').value)||48,opts:{ticks:2500,founderCount:14}},'neighborhoodOut',r=>`Beneficial >1.02: ${r.beneficial}\nNeutral 0.98–1.02: ${r.neutral}\nDeleterious <0.98: ${r.deleterious}\nMean relative: ${fmt(r.meanRelative,4)}\n\n${JSON.stringify(r.rows.slice(0,40),null,2)}`);};$('multiSeedBtn').onclick=()=>runWorker({cmd:'multiseed',base:200001,n:Number($('multiN').value)||5,ticks:Number($('multiTicks').value)||4000},'multiOut',r=>r.map(x=>`Seed ${x.seed}: pop=${x.population} gen=${fmt(x.medianGeneration,1)} repro=${fmt(x.reproductionRatePer1000MatureTicks,4)} dist=${fmt(x.meanGeneticDistance,4)} extinct=${x.extinct}`).join('\n'));$('treatmentBtn').onclick=()=>runWorker({cmd:'variant',seed:world.seed,ticks:Math.max(100,Number($('treatmentTicks').value)||2000),options:{mutationEnabled:$('tMutation').checked,reproductionMode:$('tAsexual').checked?'asexual':'sexual',objectsEnabled:$('tObjects').checked,chemicalEnabled:$('tChemical').checked,memoryEnabled:$('tMemory').checked}},'treatmentOut',r=>`Variant ${r.protocolVariantHash}\n${JSON.stringify(r.treatment,null,2)}\n\n${JSON.stringify(r.metrics,null,2)}\nState hash: ${r.stateHash}`);$('ancestryBtn').onclick=reconstructAncestry;$('persistStorageBtn').onclick=requestPersistentStorage;$('selfTestBtn').onclick=runSelfTest;
  addEventListener('beforeunload',()=>{try{saveNow('beforeunload');}catch{}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveNow('hidden');});
}

async function init(){
  bind();try{db=await openDb();}catch(err){db=null;$('saveStatus').className='saveWarn';$('saveStatus').textContent='אחסון מקומי אינו זמין — השתמש בייצוא קובץ לגיבוי.';}
  const rec=db?await latestSnapshot():null;
  if(rec){try{await loadSnapshotRecord(rec);running=false;updatePauseUi();$('saveStatus').className='saveOk';$('saveStatus').textContent=`✓ שוחזר tick ${fmt(rec.tick,0)} — לחץ הפעל להמשך`;}
    catch(err){$('saveStatus').textContent='שמירה לא תואמת: '+err.message;running=false;world=null;throw err;}}
  else newWorld(1);
  $('selfTestOut').textContent='לחץ להרצת בדיקות הליבה בעולם נפרד.';
  requestAnimationFrame(loop);
}
init().catch(err=>{console.error(err);$('saveStatus').className='saveWarn';$('saveStatus').textContent='Initialization failed: '+err.message;});
