/* Somik World Research 1.0 — Open Evolution Laboratory
   Scientific engine. No DOM access. Browser + Node compatible.
*/
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  else root.SomikResearch=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

const TAU=Math.PI*2;
const ENGINE_VERSION='Somik World Research 1.0';
const PROTOCOL_ID='SW-R1-OEL-1.0';
const PROTOCOL_HASH='a68eb2f7f223f7c0';
const ENGINE_HASH='f8caf1a27e225286';

const Protocol=Object.freeze({
  product:ENGINE_VERSION,
  protocolId:PROTOCOL_ID,
  protocolHash:PROTOCOL_HASH,
  status:'frozen-research-1.0',
  purpose:'Long-horizon open evolutionary laboratory with heritable morphology, physiology, sensors and neural topology; no target behavior or internal fitness score.',
  world:{width:1200,height:720,topology:'2D torus',synchronous:true},
  founders:{count:72,ancestorSeed:13733069,initialEnergyFraction:0.58,initialHealth:1},
  resources:{initialPrimary:240,primaryFluxPerTick:0.22,primaryEnergyPerUnit:42,wasteEnergyPerUnit:18,tissueEnergyPerUnit:34,resourceRadius:3.5,corpseDecayTicks:5000,maxLooseResources:9000},
  objects:{count:48,minRadius:8,maxRadius:18,density:2.3},
  physics:{baseDensity:1,maxLinearSpeed:2.6,baseTurnRate:0.22,collisionIterations:1},
  brain:{minHidden:4,maxHidden:32,minRaySensors:2,maxRaySensors:12,actuators:['left_motor','right_motor','jaw','grip','chemical_emit'],fixedSensors:['energy','health','touch','chemical'],activation:'tanh',recurrent:true},
  mutation:{traitSigma:0.08,weightSigma:0.14,biasSigma:0.10,basePerGene:0.008,baseStructural:0.0025,rateHeritable:true,structuralHeritable:true},
  reproduction:{mode:'sexual-hermaphroditic',maturityBaseTicks:300,cooldownBaseTicks:260,minContributionEnergy:18,developmentEfficiency:0.82,asexualControlAvailable:true},
  ecology:{predation:true,scavenging:true,wasteCrossFeeding:true,genericGrip:true,chemicalField:true,hazard:false,populationFeedback:false,rescue:false},
  observer:{feedbackToWorld:false,checkpointGenerations:[50,150,300],periodicCheckpointEveryGeneration:250,archiveBaseStride:250,archiveMaxPerLevel:4096,fixedAgeEndpoint:5000},
  controls:['mutation-off','asexual-control','no-objects','no-chemical','ancestor-replay','common-garden','connection-knockout','mutational-neighborhood','multi-seed'],
  frozenRules:['No mid-run parameter edits','No population rescue','Resource flux independent of population','Display/analytics must not consume simulation RNG','Extinction is a valid result']
});

const Limits=Object.freeze({
  radius:[3.5,13], motorPower:[0.35,2.0], basalScale:[0.45,2.1], storageScale:[0.55,2.0],
  digest:[0,1], repair:[0,1], armor:[0,1], maturityScale:[0.45,2.0], reproInvestment:[0.12,0.42],
  mutationRate:[0.001,0.04], structuralRate:[0.0002,0.012], jawPower:[0,1], gripPower:[0,1],
  chemoEmit:[0,1], chemoSense:[0,1], sensorRange:[25,180], sensorGain:[0.2,2.0]
});

function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function lerp(a,b,t){return a+(b-a)*t;}
function mean(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0;}
function median(a){if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2;}
function variance(a){if(a.length<2)return 0;const m=mean(a);return a.reduce((s,v)=>s+(v-m)*(v-m),0)/(a.length-1);}
function normSeed(v){v=(Number(v)>>>0);return v||1;}
function mix32(x){x=normSeed(x);x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return x>>>0;}
function labelHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function deriveSeed(seed,label){return mix32((normSeed(seed)^labelHash(label))>>>0);}
function eventSeed(seed,label,tick,a=0,b=0,c=0){let x=deriveSeed(seed,label);x^=Math.imul((tick+1)>>>0,0x9e3779b1);x^=Math.imul((a+1)>>>0,0x85ebca6b);x^=Math.imul((b+1)>>>0,0xc2b2ae35);x^=Math.imul((c+1)>>>0,0x27d4eb2f);return mix32(x>>>0);}
function keyed01(seed,label,tick,a=0,b=0,c=0){return eventSeed(seed,label,tick,a,b,c)/4294967296;}
function keyedGauss(seed,label,tick,a=0,b=0,c=0){let u=keyed01(seed,label+'u',tick,a,b,c),v=keyed01(seed,label+'v',tick,a,b,c);u=Math.max(u,1e-12);return Math.sqrt(-2*Math.log(u))*Math.cos(TAU*v);}

class RNG{
  constructor(seed){this.state=normSeed(seed);this.spare=null;}
  next(){this.state=(this.state+0x6D2B79F5)>>>0;let t=this.state;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;}
  int(n){return Math.floor(this.next()*n);}
  gauss(){if(this.spare!==null){const x=this.spare;this.spare=null;return x;}let u=0;while(u<=1e-12)u=this.next();const v=this.next(),m=Math.sqrt(-2*Math.log(u));this.spare=m*Math.sin(TAU*v);return m*Math.cos(TAU*v);}
  dump(){return{state:this.state,spare:this.spare};}
  static load(o){const r=new RNG(o?.state||1);r.state=normSeed(o?.state||1);r.spare=o?.spare??null;return r;}
}

function wrap(v,size){v%=size;if(v<0)v+=size;return v;}
function torusDelta(a,b,size){let d=b-a;if(d>size/2)d-=size;if(d<-size/2)d+=size;return d;}
function dist2(ax,ay,bx,by,w=Protocol.world.width,h=Protocol.world.height){const dx=torusDelta(ax,bx,w),dy=torusDelta(ay,by,h);return dx*dx+dy*dy;}
function angleDiff(a,b){let d=(b-a)%TAU;if(d>Math.PI)d-=TAU;if(d<-Math.PI)d+=TAU;return d;}
function hex32(x){return (x>>>0).toString(16).padStart(8,'0');}

class SpatialGrid{
  constructor(w,h,cell=72){this.w=w;this.h=h;this.cell=cell;this.nx=Math.ceil(w/cell);this.ny=Math.ceil(h/cell);this.cells=Array.from({length:this.nx*this.ny},()=>[]);}
  clear(){for(const c of this.cells)c.length=0;}
  key(x,y){let ix=Math.floor(wrap(x,this.w)/this.cell)%this.nx,iy=Math.floor(wrap(y,this.h)/this.cell)%this.ny;return iy*this.nx+ix;}
  add(v,x=v.x,y=v.y){this.cells[this.key(x,y)].push(v);}
  nearby(x,y,range){const ix=Math.floor(wrap(x,this.w)/this.cell)%this.nx,iy=Math.floor(wrap(y,this.h)/this.cell)%this.ny,r=Math.ceil(range/this.cell),out=[];for(let oy=-r;oy<=r;oy++)for(let ox=-r;ox<=r;ox++){let xx=(ix+ox)%this.nx;if(xx<0)xx+=this.nx;let yy=(iy+oy)%this.ny;if(yy<0)yy+=this.ny;out.push(...this.cells[yy*this.nx+xx]);}return out;}
}

const TraitKeys=['radius','motorPower','basalScale','storageScale','digestPrimary','digestWaste','digestTissue','repair','armor','maturityScale','reproInvestment','mutationRate','structuralRate','jawPower','gripPower','chemoEmit','chemoSense'];
function clampTrait(k,v){switch(k){
  case'radius':return clamp(v,...Limits.radius);case'motorPower':return clamp(v,...Limits.motorPower);case'basalScale':return clamp(v,...Limits.basalScale);case'storageScale':return clamp(v,...Limits.storageScale);
  case'digestPrimary':case'digestWaste':case'digestTissue':return clamp(v,...Limits.digest);case'repair':return clamp(v,...Limits.repair);case'armor':return clamp(v,...Limits.armor);case'maturityScale':return clamp(v,...Limits.maturityScale);case'reproInvestment':return clamp(v,...Limits.reproInvestment);case'mutationRate':return clamp(v,...Limits.mutationRate);case'structuralRate':return clamp(v,...Limits.structuralRate);case'jawPower':return clamp(v,...Limits.jawPower);case'gripPower':return clamp(v,...Limits.gripPower);case'chemoEmit':return clamp(v,...Limits.chemoEmit);case'chemoSense':return clamp(v,...Limits.chemoSense);default:return v;}}

function cloneGenome(g){return JSON.parse(JSON.stringify(g));}
function genomeHash(g){let h=2166136261>>>0;function add(x){const s=typeof x==='number'?String(Math.round(x*1e6)):String(x);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}}TraitKeys.forEach(k=>add(g.traits[k]));[...g.sensors].sort((a,b)=>String(a.id).localeCompare(String(b.id))).forEach(s=>{add(s.id);add(s.angle);add(s.range);add(s.gain);});[...g.hidden].sort((a,b)=>String(a.id).localeCompare(String(b.id))).forEach(n=>{add(n.id);add(n.bias);});[...g.connections].sort((a,b)=>String(a.id).localeCompare(String(b.id))).forEach(c=>{add(c.id);add(c.from);add(c.to);add(c.weight);add(c.enabled?1:0);});return hex32(h);}
function phenotypeVector(g){return[...TraitKeys.map(k=>g.traits[k]),g.sensors.length,g.hidden.length,g.connections.filter(c=>c.enabled).length];}

function normalizeAncestry(m,fallback){const out={};if(m&&typeof m==='object')for(const [k,v] of Object.entries(m)){const n=Number(v);if(n>0)out[k]=n;}if(!Object.keys(out).length&&fallback)out[String(fallback)]=1;const z=Object.values(out).reduce((a,b)=>a+b,0)||1;for(const k of Object.keys(out))out[k]/=z;return out;}
function combineAncestry(a,b){const out={};const aa=normalizeAncestry(a.ancestry,a.lineageRoot),bb=b?normalizeAncestry(b.ancestry,b.lineageRoot):aa;const wa=b?0.5:1,wb=b?0.5:0;for(const [k,v] of Object.entries(aa))out[k]=(out[k]||0)+v*wa;if(b)for(const [k,v] of Object.entries(bb))out[k]=(out[k]||0)+v*wb;return normalizeAncestry(out,null);}
function addWeightedMap(dst,src,weight=1){for(const [k,v] of Object.entries(src||{}))dst[k]=(dst[k]||0)+v*weight;}
function genomeDistance(a,b){const av=phenotypeVector(a),bv=phenotypeVector(b);let s=0;for(let i=0;i<av.length;i++){const scale=Math.max(1,Math.abs(av[i]),Math.abs(bv[i]));const d=(av[i]-bv[i])/scale;s+=d*d;}const ac=new Map(a.connections.map(c=>[c.id,c.weight])),bc=new Map(b.connections.map(c=>[c.id,c.weight]));const ids=new Set([...ac.keys(),...bc.keys()]);let cs=0;for(const id of ids){const x=ac.get(id)||0,y=bc.get(id)||0;cs+=(x-y)*(x-y);}return Math.sqrt(s/av.length)+(ids.size?Math.sqrt(cs/ids.size)*0.25:0);}

function founderGenome(){const r=new RNG(Protocol.founders.ancestorSeed);const traits={radius:6.4,motorPower:1,basalScale:1,storageScale:1,digestPrimary:0.66,digestWaste:0.12,digestTissue:0.10,repair:0.16,armor:0.10,maturityScale:1,reproInvestment:0.24,mutationRate:Protocol.mutation.basePerGene,structuralRate:Protocol.mutation.baseStructural,jawPower:0.28,gripPower:0.20,chemoEmit:0.08,chemoSense:0.10};
  const sensors=[];for(let i=0;i<6;i++)sensors.push({id:'r'+i,angle:(i/6)*TAU,range:82,gain:1});
  const hidden=[];for(let i=0;i<8;i++)hidden.push({id:'h'+i,bias:r.gauss()*0.08});
  const fixed=['energy','health','touch','chemical',...sensors.map(s=>'ray:'+s.id)];const acts=['act:left_motor','act:right_motor','act:jaw','act:grip','act:chemical_emit'];const connections=[];let ci=0;
  for(const f of fixed)for(const h of hidden)if(r.next()<0.55)connections.push({id:'c'+(ci++),from:f,to:h.id,weight:r.gauss()*0.30,enabled:true});
  for(const h1 of hidden)for(const h2 of hidden)if(r.next()<0.18)connections.push({id:'c'+(ci++),from:h1.id,to:h2.id,weight:r.gauss()*0.22,enabled:true});
  for(const h of hidden)for(const a of acts)if(r.next()<0.70)connections.push({id:'c'+(ci++),from:h.id,to:a,weight:r.gauss()*0.32,enabled:true});
  return{traits,sensors,hidden,connections};
}

function innovationId(seed,label,tick,childId,serial){return label+hex32(eventSeed(seed,label,tick,childId,serial));}
function validSources(g){return new Set(['energy','health','touch','chemical',...g.sensors.map(s=>'ray:'+s.id),...g.hidden.map(h=>h.id)]);}
function validTargets(g){return new Set([...g.hidden.map(h=>h.id),'act:left_motor','act:right_motor','act:jaw','act:grip','act:chemical_emit']);}
function sanitizeGenome(g){for(const k of TraitKeys)g.traits[k]=clampTrait(k,Number(g.traits[k]));g.sensors=g.sensors.slice(0,Protocol.brain.maxRaySensors);while(g.sensors.length<Protocol.brain.minRaySensors){const i=g.sensors.length;g.sensors.push({id:'repairS'+i,angle:i*TAU/Protocol.brain.minRaySensors,range:70,gain:1});}g.hidden=g.hidden.slice(0,Protocol.brain.maxHidden);while(g.hidden.length<Protocol.brain.minHidden){const i=g.hidden.length;g.hidden.push({id:'repairH'+i,bias:0});}const src=validSources(g),dst=validTargets(g),seen=new Set();g.connections=g.connections.filter(c=>src.has(c.from)&&dst.has(c.to)&&c.from!==c.to&&!seen.has(c.id)&&(seen.add(c.id),true));return g;}

function crossover(a,b,seed,tick,childId){const g={traits:{},sensors:[],hidden:[],connections:[]};let serial=0;for(const k of TraitKeys){const u=keyed01(seed,'crossTrait',tick,childId,serial++);g.traits[k]=u<0.45?a.traits[k]:u<0.90?b.traits[k]:(a.traits[k]+b.traits[k])/2;}
  const mergeById=(aa,bb,label)=>{const A=new Map(aa.map(x=>[x.id,x])),B=new Map(bb.map(x=>[x.id,x])),ids=[...new Set([...A.keys(),...B.keys()])].sort(),out=[];for(const id of ids){const x=A.get(id),y=B.get(id),u=keyed01(seed,label,tick,childId,labelHash(String(id)));if(x&&y){const z=cloneGenome(x);for(const k of Object.keys(z))if(k!=='id'&&typeof z[k]==='number')z[k]=u<0.5?x[k]:y[k];out.push(z);}else if(u<0.52)out.push(cloneGenome(x||y));}return out;};
  g.sensors=mergeById(a.sensors,b.sensors,'crossSensor');g.hidden=mergeById(a.hidden,b.hidden,'crossHidden');g.connections=mergeById(a.connections,b.connections,'crossConn');return sanitizeGenome(g);
}

function mutateGenome(parent,seed,tick,childId,enabled=true){const g=cloneGenome(parent),changes=[];if(!enabled)return{genome:g,changes};let serial=0;const p=clamp(g.traits.mutationRate,...Limits.mutationRate),sp=clamp(g.traits.structuralRate,...Limits.structuralRate);
  for(const k of TraitKeys){const u=keyed01(seed,'mutTrait',tick,childId,serial++);if(u<p){const old=g.traits[k],scale=(k==='mutationRate'||k==='structuralRate')?0.20:Protocol.mutation.traitSigma;let nv;if(k==='mutationRate'||k==='structuralRate')nv=old*Math.exp(keyedGauss(seed,'mutTraitG',tick,childId,serial++)*scale);else nv=old+keyedGauss(seed,'mutTraitG',tick,childId,serial++)*scale*Math.max(0.2,Math.abs(old));g.traits[k]=clampTrait(k,nv);changes.push({type:'trait',target:k,from:old,to:g.traits[k]});}}
  for(const s of g.sensors){for(const k of ['angle','range','gain'])if(keyed01(seed,'mutSensor',tick,childId,serial++)<p){const old=s[k],sd=k==='angle'?0.18:k==='range'?9:0.10;s[k]+=keyedGauss(seed,'mutSensorG',tick,childId,serial++)*sd;if(k==='angle')s[k]=wrap(s[k],TAU);if(k==='range')s[k]=clamp(s[k],...Limits.sensorRange);if(k==='gain')s[k]=clamp(s[k],...Limits.sensorGain);changes.push({type:'sensor',target:s.id+'.'+k,from:old,to:s[k]});}}
  for(const h of g.hidden)if(keyed01(seed,'mutBias',tick,childId,serial++)<p){const old=h.bias;h.bias+=keyedGauss(seed,'mutBiasG',tick,childId,serial++)*Protocol.mutation.biasSigma;changes.push({type:'bias',target:h.id,from:old,to:h.bias});}
  for(const c of g.connections)if(keyed01(seed,'mutWeight',tick,childId,serial++)<p){const old=c.weight;c.weight+=keyedGauss(seed,'mutWeightG',tick,childId,serial++)*Protocol.mutation.weightSigma;changes.push({type:'weight',target:c.id,from:old,to:c.weight});}
  if(keyed01(seed,'dupSensor',tick,childId,0)<sp&&g.sensors.length<Protocol.brain.maxRaySensors){const src=g.sensors[Math.floor(keyed01(seed,'dupSensorPick',tick,childId,0)*g.sensors.length)],n=cloneGenome(src);n.id=innovationId(seed,'s',tick,childId,serial++);n.angle=wrap(n.angle+keyedGauss(seed,'dupSensorAngle',tick,childId,0)*0.16,TAU);g.sensors.push(n);changes.push({type:'structure',action:'sensor_duplicate',target:n.id});}
  if(keyed01(seed,'delSensor',tick,childId,0)<sp&&g.sensors.length>Protocol.brain.minRaySensors){const i=Math.floor(keyed01(seed,'delSensorPick',tick,childId,0)*g.sensors.length),id=g.sensors[i].id;g.sensors.splice(i,1);g.connections=g.connections.filter(c=>c.from!=='ray:'+id);changes.push({type:'structure',action:'sensor_delete',target:id});}
  if(keyed01(seed,'addHidden',tick,childId,0)<sp&&g.hidden.length<Protocol.brain.maxHidden){const id=innovationId(seed,'h',tick,childId,serial++);g.hidden.push({id,bias:keyedGauss(seed,'addHiddenBias',tick,childId,0)*0.05});changes.push({type:'structure',action:'hidden_add',target:id});}
  if(keyed01(seed,'delHidden',tick,childId,0)<sp&&g.hidden.length>Protocol.brain.minHidden){const i=Math.floor(keyed01(seed,'delHiddenPick',tick,childId,0)*g.hidden.length),id=g.hidden[i].id;g.hidden.splice(i,1);g.connections=g.connections.filter(c=>c.from!==id&&c.to!==id);changes.push({type:'structure',action:'hidden_delete',target:id});}
  if(keyed01(seed,'addConn',tick,childId,0)<sp*2){const src=[...validSources(g)],dst=[...validTargets(g)];for(let tries=0;tries<8;tries++){const from=src[Math.floor(keyed01(seed,'addConnS',tick,childId,tries)*src.length)],to=dst[Math.floor(keyed01(seed,'addConnT',tick,childId,tries)*dst.length)];if(from===to||g.connections.some(c=>c.from===from&&c.to===to))continue;const id=innovationId(seed,'c',tick,childId,serial++);g.connections.push({id,from,to,weight:keyedGauss(seed,'addConnW',tick,childId,tries)*0.25,enabled:true});changes.push({type:'structure',action:'connection_add',target:id,from,to});break;}}
  if(keyed01(seed,'delConn',tick,childId,0)<sp&&g.connections.length>8){const i=Math.floor(keyed01(seed,'delConnPick',tick,childId,0)*g.connections.length),c=g.connections.splice(i,1)[0];changes.push({type:'structure',action:'connection_delete',target:c.id});}
  return{genome:sanitizeGenome(g),changes};
}

function phenotype(g){const t=g.traits,r=t.radius,mass=Math.PI*r*r,energyCapacity=clamp(50+mass*1.55*t.storageScale,70,320),sensorCost=g.sensors.reduce((s,x)=>s+0.000012*x.range*x.gain,0),brainCost=0.00055*g.hidden.length+0.00010*g.connections.filter(c=>c.enabled).length,organCost=0.004*(t.digestPrimary+t.digestWaste+t.digestTissue)+0.0035*t.repair+0.004*t.armor+0.003*t.jawPower+0.0025*t.gripPower+0.002*(t.chemoEmit+t.chemoSense)+sensorCost,baseMet=0.0105*Math.pow(mass/120,0.72)*t.basalScale+brainCost+organCost,maxSpeed=Protocol.physics.maxLinearSpeed*t.motorPower/Math.sqrt(Math.max(0.45,mass/128)),turnRate=Protocol.physics.baseTurnRate*t.motorPower/Math.pow(Math.max(0.5,mass/128),0.35),maturity=Protocol.reproduction.maturityBaseTicks*t.maturityScale,cooldown=Protocol.reproduction.cooldownBaseTicks*(0.8+0.4*t.maturityScale),reproThreshold=Math.max(42,energyCapacity*0.58),toughness=1+2.4*t.armor;return{radius:r,mass,energyCapacity,baseMet,maxSpeed,turnRate,maturity,cooldown,reproThreshold,toughness,brainCost,organCost};}

function nodeValue(map,id){return map.get(id)||0;}
function brainStep(agent,inputs){const g=agent.genome,prev=agent.hiddenState||{},next={},incoming=new Map();for(const c of g.connections){if(!c.enabled)continue;if(!incoming.has(c.to))incoming.set(c.to,[]);incoming.get(c.to).push(c);}for(const h of g.hidden){let s=h.bias;for(const c of incoming.get(h.id)||[]){let v=0;if(c.from.startsWith('ray:')||['energy','health','touch','chemical'].includes(c.from))v=inputs[c.from]||0;else v=prev[c.from]||0;s+=v*c.weight;}next[h.id]=Math.tanh(s);}const out={left_motor:0,right_motor:0,jaw:0,grip:0,chemical_emit:0};for(const k of Object.keys(out)){let s=0;for(const c of incoming.get('act:'+k)||[]){const v=next[c.from]??prev[c.from]??inputs[c.from]??0;s+=v*c.weight;}out[k]=Math.tanh(s);}agent.hiddenState=next;agent.outputs={left_motor:out.left_motor,right_motor:out.right_motor,jaw:(out.jaw+1)/2,grip:(out.grip+1)/2,chemical_emit:(out.chemical_emit+1)/2};return agent.outputs;}

class Agent{
  constructor(o){this.kind='agent';Object.assign(this,{id:o.id,x:o.x,y:o.y,dir:o.dir,genome:o.genome,energy:o.energy,health:o.health??1,age:o.age||0,generation:o.generation||0,bornTick:o.bornTick||0,lastBirthTick:o.lastBirthTick??-1e12,offspring:o.offspring||0,parentA:o.parentA||0,parentB:o.parentB||0,lineageRoot:o.lineageRoot||o.id,ancestry:normalizeAncestry(o.ancestry,o.lineageRoot||o.id),holding:o.holding||null,distance:o.distance||0,matureTicks:o.matureTicks||0,foodPrimary:o.foodPrimary||0,foodWaste:o.foodWaste||0,foodTissue:o.foodTissue||0,damageGiven:o.damageGiven||0,damageTaken:o.damageTaken||0,gripTicks:o.gripTicks||0,chemicalTotal:o.chemicalTotal||0,evalRecorded:o.evalRecorded||false},o);this.hiddenState=o.hiddenState||{};this.outputs=o.outputs||{left_motor:0,right_motor:0,jaw:0,grip:0,chemical_emit:0};this.lastInputs=o.lastInputs||{};this.touch=o.touch||0;this.lastEmit=o.lastEmit||0;this.pheno=phenotype(this.genome);}
  dump(){const o={...this};delete o.pheno;return o;}
}

function resourceEnergy(material){return material==='primary'?Protocol.resources.primaryEnergyPerUnit:material==='waste'?Protocol.resources.wasteEnergyPerUnit:Protocol.resources.tissueEnergyPerUnit;}
function digestEfficiency(agent,material){const t=agent.genome.traits;return material==='primary'?t.digestPrimary:material==='waste'?t.digestWaste:t.digestTissue;}
function entityRadius(e){if(e.kind==='agent')return e.pheno.radius;if(e.kind==='object'||e.kind==='corpse')return e.radius;return Protocol.resources.resourceRadius;}
function entityMass(e){if(!e)return 0;if(e.kind==='object')return e.mass;if(e.kind==='corpse')return Math.max(1,e.biomass*12);if(e.kind==='resource')return Math.max(.2,e.amount*4);return e.kind==='agent'?e.pheno.mass:1;}

class MultiResolutionArchive{
  constructor(baseStride=Protocol.observer.archiveBaseStride,maxPerLevel=Protocol.observer.archiveMaxPerLevel){this.baseStride=baseStride;this.maxPerLevel=maxPerLevel;this.levels=[[]];this.lastTick=-1;}
  add(sample){if(sample.tick===this.lastTick||sample.tick%this.baseStride!==0)return;this.lastTick=sample.tick;this.levels[0].push(sample);this.compact(0);}
  compact(level){while(this.levels[level]&&this.levels[level].length>this.maxPerLevel){if(!this.levels[level+1])this.levels[level+1]=[];const src=this.levels[level],move=[];for(let i=0;i<src.length-1;i+=2)move.push(src[i]);this.levels[level]=src.slice(src.length%2?src.length-1:src.length);this.levels[level+1].push(...move);level++;}}
  dump(){return{baseStride:this.baseStride,maxPerLevel:this.maxPerLevel,levels:this.levels,lastTick:this.lastTick};}
  static load(o){const a=new MultiResolutionArchive(o.baseStride,o.maxPerLevel);a.levels=o.levels||[[]];a.lastTick=o.lastTick??-1;return a;}
  flattened(limit=5000){const a=[];for(let l=this.levels.length-1;l>=0;l--)a.push(...this.levels[l]);a.sort((x,y)=>x.tick-y.tick);return a.slice(-limit);}
}

class World{
  constructor(opts={}){
    this.seed=normSeed(opts.seed||1);this.treatment={mutationEnabled:opts.mutationEnabled!==false,reproductionMode:opts.reproductionMode||'sexual',objectsEnabled:opts.objectsEnabled!==false,chemicalEnabled:opts.chemicalEnabled!==false};this.protocolVariantHash=this.variantHash();
    this.rngInit=new RNG(deriveSeed(this.seed,'initialization'));this.rngEnvironment=new RNG(deriveSeed(this.seed,'environment-primary'));this.ancestorGenome=cloneGenome(opts.founderGenome||founderGenome());this.ancestorHash=genomeHash(this.ancestorGenome);
    this.tick=0;this.nextAgentId=1;this.nextResourceId=1;this.nextObjectId=1;this.births=0;this.deaths=0;this.extinct=false;this.technicalFailure=false;this.resourceAccumulator=0;this.agents=[];this.resources=[];this.objects=[];this.corpses=[];this.eventBuffer=[];this.recentEvents=[];this.lineageRecent=new Map();this.archive=new MultiResolutionArchive();this.checkpoints={};this.checkpointDone=new Set();this.noveltyArchive=[];this.fixedAgeN=0;this.fixedAgeOffspring=0;this.fixedAgeReproduced=0;this.completedN=0;this.completedOffspring=0;this.completedReproduced=0;this.ecology={consumedPrimary:0,consumedWaste:0,consumedTissue:0,predationDamage:0,bites:0,grips:0,objectCarryTicks:0,chemicalEmission:0,wasteProduced:0,corpsesCreated:0};this.matureExposure=0;this.lastClusterCount=1;this.cohortStats={};this.mutationStats={birthsWithMutations:0,totalChanges:0,byType:{trait:0,sensor:0,bias:0,weight:0,structure:0},byAction:{},byTarget:{}};this.startObserverTime=Date.now();
    const founderCount=opts.founderCount||Protocol.founders.count;for(let i=0;i<founderCount;i++){const g=cloneGenome(this.ancestorGenome),p=phenotype(g);const a=new Agent({id:this.nextAgentId++,x:this.rngInit.next()*Protocol.world.width,y:this.rngInit.next()*Protocol.world.height,dir:this.rngInit.next()*TAU,genome:g,energy:p.energyCapacity*Protocol.founders.initialEnergyFraction,health:1,generation:0,lineageRoot:i+1,ancestry:{[String(i+1)]:1}});this.agents.push(a);this.recordLineage(a);}
    for(let i=0;i<Protocol.resources.initialPrimary;i++)this.resources.push(this.makeResource('primary',1,this.rngInit.next()*Protocol.world.width,this.rngInit.next()*Protocol.world.height));
    if(this.treatment.objectsEnabled)for(let i=0;i<Protocol.objects.count;i++){const r=lerp(Protocol.objects.minRadius,Protocol.objects.maxRadius,this.rngInit.next());this.objects.push({kind:'object',id:this.nextObjectId++,x:this.rngInit.next()*Protocol.world.width,y:this.rngInit.next()*Protocol.world.height,radius:r,mass:Math.PI*r*r*Protocol.objects.density,heldBy:0});}
    this.captureCheckpoint(0);
  }
  variantHash(){return hex32(labelHash(JSON.stringify(this.treatment)));}
  makeResource(material,amount,x,y){return{kind:'resource',id:this.nextResourceId++,material,amount,x:wrap(x,Protocol.world.width),y:wrap(y,Protocol.world.height),heldBy:0,age:0};}
  recordLineage(a){this.lineageRecent.set(a.id,{id:a.id,parentA:a.parentA,parentB:a.parentB,generation:a.generation,bornTick:a.bornTick,genomeHash:genomeHash(a.genome),lineageRoot:a.lineageRoot});if(this.lineageRecent.size>25000){const keys=[...this.lineageRecent.keys()].sort((x,y)=>x-y);for(let i=0;i<5000;i++)this.lineageRecent.delete(keys[i]);}}
  logEvent(e){const ev={tick:this.tick,...e};this.eventBuffer.push(ev);this.recentEvents.push(ev);if(this.recentEvents.length>3000)this.recentEvents.splice(0,500);}
  buildGrid(includeResources=true){const g=new SpatialGrid(Protocol.world.width,Protocol.world.height,72);for(const a of this.agents)g.add(a,a.x,a.y);if(includeResources)for(const r of this.resources)g.add(r,r.x,r.y);for(const c of this.corpses)g.add(c,c.x,c.y);if(this.treatment.objectsEnabled)for(const o of this.objects)g.add(o,o.x,o.y);return g;}
  sensorsFor(a,grid){let maxRange=150;for(const s of a.genome.sensors)if(s.range+24>maxRange)maxRange=s.range+24;const raw=grid.nearby(a.x,a.y,maxRange),cand=[];let touching=false,chem=0;for(const q of raw){if(q.kind==='agent'&&q.id===a.id)continue;const rr=entityRadius(q),dx=torusDelta(a.x,q.x,Protocol.world.width),dy=torusDelta(a.y,q.y,Protocol.world.height),center=Math.hypot(dx,dy),surface=center-rr-a.pheno.radius,qa=Math.atan2(dy,dx),angularRadius=Math.asin(clamp((rr+a.pheno.radius)/Math.max(1,center),-1,1));cand.push({q,dx,dy,center,surface,qa,angularRadius,rr});if(surface<=0)touching=true;if(this.treatment.chemicalEnabled&&q.kind==='agent'&&q.lastEmit&&center<150)chem+=q.lastEmit*(1-center/150);}
    const inputs={energy:clamp(a.energy/a.pheno.energyCapacity,0,1)*2-1,health:clamp(a.health,0,1)*2-1,touch:touching?1:-1,chemical:this.treatment.chemicalEnabled?Math.tanh(chem*0.4*a.genome.traits.chemoSense):0};a.touch=touching?1:0;
    for(const s of a.genome.sensors){let best=s.range,ang=a.dir+s.angle;for(const c of cand){if(c.surface<0){best=0;break;}if(c.surface>s.range)continue;const ad=Math.abs(angleDiff(ang,c.qa));if(ad<=Math.max(0.055,c.angularRadius)&&c.surface<best)best=c.surface;}inputs['ray:'+s.id]=clamp((1-best/s.range)*s.gain,0,1)*2-1;}return inputs;
  }
  actionPhase(grid){const proposals=[];for(const a of this.agents){const input=this.sensorsFor(a,grid);a.lastInputs=input;const o=brainStep(a,input),p=a.pheno;const turn=(o.right_motor-o.left_motor)*p.turnRate,drive=(o.right_motor+o.left_motor)*0.5,dir=wrap(a.dir+turn,TAU),speed=drive*p.maxSpeed,dx=Math.cos(dir)*speed,dy=Math.sin(dir)*speed;proposals.push({id:a.id,x:wrap(a.x+dx,Protocol.world.width),y:wrap(a.y+dy,Protocol.world.height),dir,dx,dy,speed,outputs:o});}return proposals;}
  resolveAgentCollisions(proposals){const map=new Map(proposals.map(p=>[p.id,p])),agentMap=new Map(this.agents.map(a=>[a.id,a])),g=new SpatialGrid(Protocol.world.width,Protocol.world.height,40);for(const p of proposals){const a=agentMap.get(p.id);g.add({kind:'agent',id:p.id,x:p.x,y:p.y,radius:a.pheno.radius,mass:a.pheno.mass},p.x,p.y);}const disp=new Map(this.agents.map(a=>[a.id,{x:0,y:0}])),seen=new Set();for(const a of this.agents){const p=map.get(a.id);for(const q of g.nearby(p.x,p.y,a.pheno.radius*2+26)){if(q.id===a.id)continue;const lo=Math.min(a.id,q.id),hi=Math.max(a.id,q.id),key=lo+':'+hi;if(seen.has(key))continue;seen.add(key);const b=agentMap.get(q.id);if(!b)continue;const pb=map.get(b.id);let dx=torusDelta(pb.x,p.x,Protocol.world.width),dy=torusDelta(pb.y,p.y,Protocol.world.height),d=Math.hypot(dx,dy),minD=a.pheno.radius+b.pheno.radius;if(d>=minD)continue;if(d<1e-9){const ang=keyed01(this.seed,'overlap',this.tick,lo,hi)*TAU;dx=Math.cos(ang);dy=Math.sin(ang);d=1;}const ov=minD-d,nx=dx/d,ny=dy/d,ma=a.pheno.mass,mb=b.pheno.mass,total=ma+mb,da=ov*(mb/total),db=ov*(ma/total);disp.get(a.id).x+=nx*da;disp.get(a.id).y+=ny*da;disp.get(b.id).x-=nx*db;disp.get(b.id).y-=ny*db;}}for(const p of proposals){const d=disp.get(p.id);p.x=wrap(p.x+d.x,Protocol.world.width);p.y=wrap(p.y+d.y,Protocol.world.height);}return map;
  }
  resolveObjects(proposals){if(!this.treatment.objectsEnabled)return;const movableByKey=new Map();for(const o of this.objects)movableByKey.set('object:'+o.id,o);for(const r of this.resources)movableByKey.set('resource:'+r.id,r);for(const c of this.corpses)movableByKey.set('corpse:'+c.id,c);
    for(const a of this.agents){const p=proposals.get(a.id);if(!p)continue;if(a.holding){const e=movableByKey.get(a.holding.kind+':'+a.holding.id);if(!e){a.holding=null;}else if(a.outputs.grip<0.32){e.heldBy=0;a.holding=null;}else{e.heldBy=a.id;e.x=wrap(p.x+Math.cos(p.dir)*(a.pheno.radius+entityRadius(e)+2),Protocol.world.width);e.y=wrap(p.y+Math.sin(p.dir)*(a.pheno.radius+entityRadius(e)+2),Protocol.world.height);a.gripTicks++;this.ecology.objectCarryTicks++;}}
      if(!a.holding&&a.outputs.grip>0.70&&a.genome.traits.gripPower>0.05){let best=null,bd=1e9;const pool=[...this.objects,...this.resources,...this.corpses];for(const e of pool){if(e.heldBy)continue;const d=Math.sqrt(dist2(p.x,p.y,e.x,e.y))-a.pheno.radius-entityRadius(e);if(d<3&&d<bd){best=e;bd=d;}}if(best){best.heldBy=a.id;a.holding={kind:best.kind,id:best.id};this.ecology.grips++;this.logEvent({type:'grip',agent:a.id,entityKind:best.kind,entity:best.id});}}
    }
    for(const o of this.objects){if(o.heldBy)continue;let px=0,py=0,count=0;for(const a of this.agents){const p=proposals.get(a.id);const dx=torusDelta(o.x,p.x,Protocol.world.width),dy=torusDelta(o.y,p.y,Protocol.world.height),d=Math.hypot(dx,dy),md=o.radius+a.pheno.radius;if(d<md&&d>1e-9){const ov=md-d,nx=dx/d,ny=dy/d;p.x=wrap(p.x+nx*ov*0.65,Protocol.world.width);p.y=wrap(p.y+ny*ov*0.65,Protocol.world.height);const push=(Math.abs(a.outputs.left_motor)+Math.abs(a.outputs.right_motor))*a.genome.traits.motorPower;px-=nx*ov*0.35*push;py-=ny*ov*0.35*push;count++;}}if(count){o.x=wrap(o.x+px/Math.max(1,o.mass/80),Protocol.world.width);o.y=wrap(o.y+py/Math.max(1,o.mass/80),Protocol.world.height);}}
  }
  applyMotionEnergy(proposals){for(const a of this.agents){const p=proposals.get(a.id);if(!p)continue;const oldx=a.x,oldy=a.y;a.x=p.x;a.y=p.y;a.dir=p.dir;const dd=Math.sqrt(dist2(oldx,oldy,a.x,a.y));a.distance+=dd;a.age++;if(a.age>=a.pheno.maturity)a.matureTicks++,this.matureExposure++;let cost=a.pheno.baseMet+(Math.abs(a.outputs.left_motor)+Math.abs(a.outputs.right_motor))*0.5*0.010*a.pheno.mass/125*a.genome.traits.motorPower;if(a.holding){let e=null;if(a.holding.kind==='object')e=this.objects.find(x=>x.id===a.holding.id);else if(a.holding.kind==='resource')e=this.resources.find(x=>x.id===a.holding.id);else if(a.holding.kind==='corpse')e=this.corpses.find(x=>x.id===a.holding.id);if(e)cost+=0.0035*entityMass(e)/100;}const emit=this.treatment.chemicalEnabled?a.outputs.chemical_emit*a.genome.traits.chemoEmit:0;a.lastEmit=emit;a.chemicalTotal+=emit;this.ecology.chemicalEmission+=emit;cost+=emit*0.006;a.energy-=cost;if(a.health<1&&a.energy>2&&a.genome.traits.repair>0){const repair=Math.min(1-a.health,0.0006*a.genome.traits.repair);a.health+=repair;a.energy-=repair*8;}a.energy=clamp(a.energy,-50,a.pheno.energyCapacity);}}
  mouthTarget(a,grid){const reach=a.pheno.radius+7;let best=null,bd=Infinity;for(const q of grid.nearby(a.x,a.y,reach+22)){if(q.kind==='agent'&&q.id===a.id)continue;const dx=torusDelta(a.x,q.x,Protocol.world.width),dy=torusDelta(a.y,q.y,Protocol.world.height),d=Math.hypot(dx,dy)-a.pheno.radius-entityRadius(q),ad=Math.abs(angleDiff(a.dir,Math.atan2(dy,dx)));if(d<=5&&ad<0.70&&d<bd){best=q;bd=d;}}return best;}
  feedingAndPredation(){const grid=this.buildGrid(true),resourceDelete=new Set(),corpseDelete=new Set(),waste=[],groups=new Map();for(const a of this.agents){const act=a.outputs.jaw*a.genome.traits.jawPower;if(act<0.12)continue;const q=this.mouthTarget(a,grid);if(!q||q.kind==='object')continue;this.ecology.bites++;const key=q.kind+':'+q.id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push({a,q,act,key:eventSeed(this.seed,'jawTie',this.tick,a.id,q.id)});}for(const intents of groups.values()){intents.sort((x,y)=>x.key-y.key||x.a.id-y.a.id);const q=intents[0].q;if(q.kind==='resource'){const r=q;let available=Math.max(0,r.amount);for(const it of intents){if((r.heldBy&&r.heldBy!==it.a.id)||available<=0)continue;const take=Math.min(available,0.20+0.55*it.act),eff=digestEfficiency(it.a,r.material),gain=take*resourceEnergy(r.material)*eff;it.a.energy=Math.min(it.a.pheno.energyCapacity,it.a.energy+gain);available-=take;if(r.material==='primary'){it.a.foodPrimary+=take;this.ecology.consumedPrimary+=take;}else if(r.material==='waste'){it.a.foodWaste+=take;this.ecology.consumedWaste+=take;}else{it.a.foodTissue+=take;this.ecology.consumedTissue+=take;}const wasteAmt=take*(1-eff)*0.52;if(wasteAmt>0.06)waste.push(this.makeResource('waste',wasteAmt,it.a.x,it.a.y));this.ecology.wasteProduced+=wasteAmt;}r.amount=available;if(r.amount<=0.04)resourceDelete.add(r.id);}else if(q.kind==='corpse'){const c=q;let available=Math.max(0,c.biomass);for(const it of intents){if((c.heldBy&&c.heldBy!==it.a.id)||available<=0)continue;const take=Math.min(available,0.15+0.65*it.act),eff=it.a.genome.traits.digestTissue;it.a.energy=Math.min(it.a.pheno.energyCapacity,it.a.energy+take*Protocol.resources.tissueEnergyPerUnit*eff);it.a.foodTissue+=take;this.ecology.consumedTissue+=take;available-=take;}c.biomass=available;if(c.biomass<=0.05)corpseDelete.add(c.id);}else if(q.kind==='agent'&&Protocol.ecology.predation){const victim=q;let remaining=Math.max(0,victim.health);for(const it of intents){if(it.a.id===victim.id||remaining<=0)continue;const proposed=0.0014*it.act*it.a.pheno.mass/(100*victim.pheno.toughness),damage=Math.min(remaining,proposed);remaining-=damage;it.a.damageGiven+=damage;victim.damageTaken+=damage;this.ecology.predationDamage+=damage;const gain=damage*45*it.a.genome.traits.digestTissue;it.a.energy=Math.min(it.a.pheno.energyCapacity,it.a.energy+gain);}victim.health=remaining;}}if(resourceDelete.size){this.resources=this.resources.filter(r=>!resourceDelete.has(r.id));for(const a of this.agents)if(a.holding?.kind==='resource'&&resourceDelete.has(a.holding.id))a.holding=null;}if(corpseDelete.size){this.corpses=this.corpses.filter(c=>!corpseDelete.has(c.id));for(const a of this.agents)if(a.holding?.kind==='corpse'&&corpseDelete.has(a.holding.id))a.holding=null;}if(waste.length&&this.resources.length<Protocol.resources.maxLooseResources)this.resources.push(...waste.slice(0,Protocol.resources.maxLooseResources-this.resources.length));
  }
  finalizeFixedAge(a){if(a.evalRecorded)return;a.evalRecorded=true;this.fixedAgeN++;this.fixedAgeOffspring+=a.offspring;if(a.offspring>0)this.fixedAgeReproduced++;}
  killDead(){const dead=[],alive=[];for(const a of this.agents){if(a.age>=Protocol.observer.fixedAgeEndpoint&&!a.evalRecorded)this.finalizeFixedAge(a);if(a.energy<=0||a.health<=0){if(!a.evalRecorded)this.finalizeFixedAge(a);this.completedN++;this.completedOffspring+=a.offspring;if(a.offspring>0)this.completedReproduced++;dead.push(a);}else alive.push(a);}for(const a of dead){this.deaths++;const biomass=Math.max(0.3,a.pheno.mass/85+Math.max(0,a.energy)/80);this.corpses.push({kind:'corpse',id:this.nextResourceId++,x:a.x,y:a.y,radius:Math.max(4,a.pheno.radius*0.85),biomass,age:0,sourceAgent:a.id,heldBy:0});this.ecology.corpsesCreated++;this.logEvent({type:'death',agent:a.id,generation:a.generation,genomeHash:genomeHash(a.genome),offspring:a.offspring});}this.agents=alive;if(!this.agents.length)this.extinct=true;}
  eligible(a){return a.age>=a.pheno.maturity&&a.energy>=a.pheno.reproThreshold&&this.tick-a.lastBirthTick>=a.pheno.cooldown;}
  combineAndMutate(a,b,childId){let base;if(this.treatment.reproductionMode==='asexual'||!b)base=cloneGenome(a.genome);else base=crossover(a.genome,b.genome,this.seed,this.tick,childId);return mutateGenome(base,this.seed,this.tick,childId,this.treatment.mutationEnabled);}
  reproduceSexual(){const grid=new SpatialGrid(Protocol.world.width,Protocol.world.height,42);for(const a of this.agents)grid.add(a,a.x,a.y);const candidates=[],seen=new Set();for(const a of this.agents){if(!this.eligible(a))continue;for(const b of grid.nearby(a.x,a.y,a.pheno.radius+26)){if(b.id===a.id||!this.eligible(b))continue;const lo=Math.min(a.id,b.id),hi=Math.max(a.id,b.id),k=lo+':'+hi;if(seen.has(k))continue;seen.add(k);const rr=a.pheno.radius+b.pheno.radius+1.5;if(dist2(a.x,a.y,b.x,b.y)<=rr*rr)candidates.push({a:a.id===lo?a:b,b:a.id===lo?b:a,key:eventSeed(this.seed,'mateTie',this.tick,lo,hi)});}}candidates.sort((x,y)=>x.key-y.key||x.a.id-y.a.id);const used=new Set();for(const p of candidates){if(used.has(p.a.id)||used.has(p.b.id)||!this.eligible(p.a)||!this.eligible(p.b))continue;this.makeChild(p.a,p.b);used.add(p.a.id);used.add(p.b.id);}}
  reproduceAsexual(){const eligible=this.agents.filter(a=>this.eligible(a)).sort((a,b)=>eventSeed(this.seed,'asexualOrder',this.tick,a.id)-eventSeed(this.seed,'asexualOrder',this.tick,b.id));for(const a of eligible)if(this.eligible(a))this.makeChild(a,null);}
  makeChild(a,b){const pa=a.genome.traits.reproInvestment,pb=b?b.genome.traits.reproInvestment:pa,ca=Math.min(a.energy*pa,a.pheno.energyCapacity*0.34),cb=b?Math.min(b.energy*pb,b.pheno.energyCapacity*0.34):0;if(ca<Protocol.reproduction.minContributionEnergy||(b&&cb<Protocol.reproduction.minContributionEnergy))return;const childId=this.nextAgentId++,mm=this.combineAndMutate(a,b,childId),g=mm.genome,p=phenotype(g),contrib=b?(ca+cb):ca,energy=Math.min(p.energyCapacity,contrib*Protocol.reproduction.developmentEfficiency);if(energy<15)return;a.energy-=ca;a.lastBirthTick=this.tick;a.offspring++;if(b){b.energy-=cb;b.lastBirthTick=this.tick;b.offspring++;}const mx=b?wrap(a.x+torusDelta(a.x,b.x,Protocol.world.width)*0.5,Protocol.world.width):a.x,my=b?wrap(a.y+torusDelta(a.y,b.y,Protocol.world.height)*0.5,Protocol.world.height):a.y,ang=keyed01(this.seed,'birthAngle',this.tick,childId,a.id,b?.id||0)*TAU,rad=(a.pheno.radius+(b?b.pheno.radius:a.pheno.radius))*0.9+5,x=wrap(mx+Math.cos(ang)*rad,Protocol.world.width),y=wrap(my+Math.sin(ang)*rad,Protocol.world.height),gen=Math.max(a.generation,b?b.generation:a.generation)+1,root=keyed01(this.seed,'rootChoose',this.tick,childId,a.id,b?.id||0)<0.5?a.lineageRoot:(b?b.lineageRoot:a.lineageRoot),child=new Agent({id:childId,x,y,dir:keyed01(this.seed,'birthDir',this.tick,childId)*TAU,genome:g,energy,health:1,age:0,generation:gen,bornTick:this.tick,parentA:a.id,parentB:b?.id||0,lineageRoot:root,ancestry:combineAncestry(a,b)});this.agents.push(child);this.births++;this.recordLineage(child);const bin=Math.floor(gen/50)*50;if(!this.cohortStats[bin])this.cohortStats[bin]={birthAncestry:{},eligibleExposure:{},births:0};addWeightedMap(this.cohortStats[bin].birthAncestry,child.ancestry,1);this.cohortStats[bin].births++;if(mm.changes.length){this.mutationStats.birthsWithMutations++;this.mutationStats.totalChanges+=mm.changes.length;for(const ch of mm.changes){const ty=ch.type||'other';this.mutationStats.byType[ty]=(this.mutationStats.byType[ty]||0)+1;const ac=ch.action||'';if(ac)this.mutationStats.byAction[ac]=(this.mutationStats.byAction[ac]||0)+1;const tg=ch.target||'';if(tg)this.mutationStats.byTarget[tg]=(this.mutationStats.byTarget[tg]||0)+1;}}this.logEvent({type:'birth',child:child.id,parentA:a.id,parentB:b?.id||0,generation:gen,genomeHash:genomeHash(g),ancestry:child.ancestry,mutations:mm.changes});}
  reproduction(){if(this.extinct)return;if(this.treatment.reproductionMode==='asexual')this.reproduceAsexual();else this.reproduceSexual();}
  recordAncestryExposure(){if(this.tick%10!==0)return;for(const a of this.agents){if(a.age<a.pheno.maturity)continue;const bin=Math.floor(a.generation/50)*50;if(!this.cohortStats[bin])this.cohortStats[bin]={birthAncestry:{},eligibleExposure:{},births:0};addWeightedMap(this.cohortStats[bin].eligibleExposure,a.ancestry,10);}}
  resourceFlow(){this.resourceAccumulator+=Protocol.resources.primaryFluxPerTick;while(this.resourceAccumulator>=1&&this.resources.length<Protocol.resources.maxLooseResources){this.resourceAccumulator-=1;this.resources.push(this.makeResource('primary',1,this.rngEnvironment.next()*Protocol.world.width,this.rngEnvironment.next()*Protocol.world.height));}for(const r of this.resources)r.age=(r.age||0)+1;const waste=[];for(const c of this.corpses){c.age++;if(c.age>=Protocol.resources.corpseDecayTicks&&c.biomass>0){waste.push(this.makeResource('waste',c.biomass*0.72,c.x,c.y));c.biomass=0;}}const gone=new Set(this.corpses.filter(c=>c.biomass<=0.04).map(c=>c.id));this.corpses=this.corpses.filter(c=>c.biomass>0.04);if(gone.size)for(const a of this.agents)if(a.holding?.kind==='corpse'&&gone.has(a.holding.id))a.holding=null;if(waste.length&&this.resources.length<Protocol.resources.maxLooseResources)this.resources.push(...waste.slice(0,Protocol.resources.maxLooseResources-this.resources.length));}
  step(){if(this.extinct||this.technicalFailure)return;try{const sensorGrid=this.buildGrid(true),proposals=this.actionPhase(sensorGrid),map=this.resolveAgentCollisions(proposals);this.resolveObjects(map);this.applyMotionEnergy(map);this.feedingAndPredation();this.killDead();this.reproduction();this.recordAncestryExposure();this.resourceFlow();this.tick++;this.captureObserver();if(!this.agents.length)this.extinct=true;}catch(err){this.technicalFailure=true;this.logEvent({type:'technical_failure',message:String(err?.stack||err)});}}
  phenotypeDescriptor(a){const t=a.genome.traits;return[t.radius,t.motorPower,t.basalScale,t.storageScale,t.digestPrimary,t.digestWaste,t.digestTissue,t.repair,t.armor,t.jawPower,t.gripPower,t.chemoEmit,t.chemoSense,a.genome.sensors.length,a.genome.hidden.length,a.genome.connections.length];}
  noveltyScore(sample){if(!this.noveltyArchive.length)return 0;let total=0;for(const d of sample){let best=Infinity;for(const q of this.noveltyArchive){let s=0;for(let i=0;i<d.length;i++){const z=(d[i]-q[i])/Math.max(1,Math.abs(d[i]),Math.abs(q[i]));s+=z*z;}best=Math.min(best,Math.sqrt(s/d.length));}total+=best;}return total/sample.length;}
  estimateClusters(sample){if(!sample.length)return 0;const reps=[];for(const a of sample){let found=false;for(const r of reps)if(genomeDistance(a.genome,r.genome)<0.22){found=true;break;}if(!found)reps.push(a);}return reps.length;}
  metrics(){
    const n=this.agents.length;
    const gens=this.agents.map(a=>a.generation), ages=this.agents.map(a=>a.age), ener=this.agents.map(a=>a.energy), health=this.agents.map(a=>a.health);
    const sample=this.agents.length<=120?this.agents:this.agents.filter(a=>eventSeed(this.seed,'metricSample',Math.floor(this.tick/1000),a.id)%Math.ceil(this.agents.length/120)===0).slice(0,120);
    const gd=sample.map(a=>genomeDistance(a.genome,this.ancestorGenome)), pair=[];
    for(let i=0;i<Math.min(sample.length,40);i++)for(let j=i+1;j<Math.min(sample.length,40);j++)pair.push(genomeDistance(sample[i].genome,sample[j].genome));
    const traits={};for(const k of TraitKeys)traits[k]=mean(sample.map(a=>a.genome.traits[k]));
    const avgSensors=mean(sample.map(a=>a.genome.sensors.length)),avgHidden=mean(sample.map(a=>a.genome.hidden.length)),avgConnections=mean(sample.map(a=>a.genome.connections.filter(c=>c.enabled).length));
    const desc=sample.slice(0,30).map(a=>this.phenotypeDescriptor(a)), novelty=this.noveltyScore(desc);
    const mats={primary:0,waste:0,tissue:0};for(const r of this.resources)mats[r.material]=(mats[r.material]||0)+r.amount;
    const founderMass={};for(const a of sample)addWeightedMap(founderMass,a.ancestry,1);
    const fm=Object.values(founderMass),topFounderShare=sample.length&&fm.length?Math.max(...fm)/sample.length:0;
    const ancestryEntropy=sample.length?Object.values(founderMass).reduce((z,v)=>{const p=v/sample.length;return p>0?z-p*Math.log(p):z;},0):0;
    const hashes=new Map();for(const a of sample){const h=genomeHash(a.genome);hashes.set(h,(hashes.get(h)||0)+1);}const topGenomeShare=sample.length?Math.max(0,...hashes.values())/sample.length:0;
    const phenos=sample.map(a=>a.pheno||phenotype(a.genome));
    const ph={radius:mean(phenos.map(x=>x.radius)),mass:mean(phenos.map(x=>x.mass)),energyCapacity:mean(phenos.map(x=>x.energyCapacity)),baseMet:mean(phenos.map(x=>x.baseMet)),maxSpeed:mean(phenos.map(x=>x.maxSpeed)),turnRate:mean(phenos.map(x=>x.turnRate)),maturity:mean(phenos.map(x=>x.maturity)),reproThreshold:mean(phenos.map(x=>x.reproThreshold)),toughness:mean(phenos.map(x=>x.toughness))};
    const behavior={distancePer1000Age:mean(sample.map(a=>a.distance*1000/Math.max(1,a.age))),primaryPer1000Age:mean(sample.map(a=>a.foodPrimary*1000/Math.max(1,a.age))),wastePer1000Age:mean(sample.map(a=>a.foodWaste*1000/Math.max(1,a.age))),tissuePer1000Age:mean(sample.map(a=>a.foodTissue*1000/Math.max(1,a.age))),gripFraction:mean(sample.map(a=>a.gripTicks/Math.max(1,a.age))),chemicalPer1000Age:mean(sample.map(a=>a.chemicalTotal*1000/Math.max(1,a.age))),damageGivenPer1000Age:mean(sample.map(a=>a.damageGiven*1000/Math.max(1,a.age))),damageTakenPer1000Age:mean(sample.map(a=>a.damageTaken*1000/Math.max(1,a.age))),leftMotor:mean(sample.map(a=>a.outputs?.left_motor||0)),rightMotor:mean(sample.map(a=>a.outputs?.right_motor||0)),jaw:mean(sample.map(a=>a.outputs?.jaw||0)),grip:mean(sample.map(a=>a.outputs?.grip||0)),chemicalEmit:mean(sample.map(a=>a.outputs?.chemical_emit||0))};
    return{tick:this.tick,population:n,births:this.births,deaths:this.deaths,extinct:this.extinct,technicalFailure:this.technicalFailure,medianGeneration:median(gens),maxGeneration:gens.length?Math.max(...gens):0,meanAge:mean(ages),medianAge:median(ages),meanEnergy:mean(ener),meanHealth:mean(health),meanGeneticDistance:mean(gd),geneticDiversity:mean(pair),uniqueGenomeFraction:sample.length?hashes.size/sample.length:0,topGenomeShare,founderHash:this.ancestorHash,traits,phenotype:ph,behavior,avgSensors,avgHidden,avgConnections,brainComplexity:avgHidden+avgConnections*0.15,phenotypeNovelty:novelty,observerClusters:this.lastClusterCount,topFounderShare,ancestryEntropy,materials:mats,corpseBiomass:this.corpses.reduce((z,c)=>z+c.biomass,0),fixedAgeN:this.fixedAgeN,meanOffspringFixedAge:this.fixedAgeN?this.fixedAgeOffspring/this.fixedAgeN:0,reproducedFixedAgeFraction:this.fixedAgeN?this.fixedAgeReproduced/this.fixedAgeN:0,completedN:this.completedN,completedLRS:this.completedN?this.completedOffspring/this.completedN:0,completedReproducedFraction:this.completedN?this.completedReproduced/this.completedN:0,reproductionRatePer1000MatureTicks:this.matureExposure?this.births*1000/this.matureExposure:0,matureExposure:this.matureExposure,mutationStats:JSON.parse(JSON.stringify(this.mutationStats)),ecology:{...this.ecology},resources:this.resources.length,objects:this.objects.length,corpses:this.corpses.length};
  }
  captureObserver(){if(this.tick%1000===0){const sm=this.agents.slice().sort((a,b)=>eventSeed(this.seed,'clusterSample',this.tick,a.id)-eventSeed(this.seed,'clusterSample',this.tick,b.id)).slice(0,100);this.lastClusterCount=this.estimateClusters(sm);const desc=sm.slice(0,20).map(a=>this.phenotypeDescriptor(a));this.noveltyArchive.push(...desc);if(this.noveltyArchive.length>400)this.noveltyArchive.splice(0,this.noveltyArchive.length-400);}if(this.tick%Protocol.observer.archiveBaseStride===0){const m=this.metrics();this.archive.add(m);}if(this.tick%50===0){const mg=Math.floor(median(this.agents.map(a=>a.generation)));for(const cp of Protocol.observer.checkpointGenerations)if(mg>=cp&&!this.checkpointDone.has(cp))this.captureCheckpoint(cp);if(mg>=500){const p=Protocol.observer.periodicCheckpointEveryGeneration,cp=Math.floor(mg/p)*p;if(cp>=500&&!this.checkpointDone.has(cp))this.captureCheckpoint(cp);}}}
  captureCheckpoint(generation){const sample=this.agents.slice().sort((a,b)=>eventSeed(this.seed,'checkpoint',generation,a.id)-eventSeed(this.seed,'checkpoint',generation,b.id)).slice(0,16);this.checkpoints[generation]={generation,tick:this.tick,metrics:this.metrics(),genomes:sample.map(a=>cloneGenome(a.genome)),agentIds:sample.map(a=>a.id),hashes:sample.map(a=>genomeHash(a.genome))};this.checkpointDone.add(generation);this.logEvent({type:'checkpoint',generation,agentIds:sample.map(a=>a.id),hashes:sample.map(a=>genomeHash(a.genome))});}
  stateHash(){let h=2166136261>>>0;const add=s=>{s=String(s);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}};add(this.seed);add(this.tick);add(this.births);add(this.deaths);add(this.resourceAccumulator.toFixed(9));for(const a of this.agents.slice().sort((x,y)=>x.id-y.id)){add(a.id);add(a.x.toFixed(6));add(a.y.toFixed(6));add(a.energy.toFixed(6));add(a.health.toFixed(6));add(a.generation);add(genomeHash(a.genome));}for(const r of this.resources.slice().sort((x,y)=>x.id-y.id)){add(r.id);add(r.material);add(r.x.toFixed(5));add(r.y.toFixed(5));add(r.amount.toFixed(5));}return hex32(h);}
  dump(){return{schema:'SomikWorldResearchState/1',engineVersion:ENGINE_VERSION,protocolId:PROTOCOL_ID,protocolHash:PROTOCOL_HASH,engineHash:ENGINE_HASH,protocolVariantHash:this.protocolVariantHash,seed:this.seed,treatment:this.treatment,rngInit:this.rngInit.dump(),rngEnvironment:this.rngEnvironment.dump(),ancestorGenome:this.ancestorGenome,ancestorHash:this.ancestorHash,tick:this.tick,nextAgentId:this.nextAgentId,nextResourceId:this.nextResourceId,nextObjectId:this.nextObjectId,births:this.births,deaths:this.deaths,extinct:this.extinct,technicalFailure:this.technicalFailure,resourceAccumulator:this.resourceAccumulator,agents:this.agents.map(a=>a.dump()),resources:this.resources,objects:this.objects,corpses:this.corpses,eventBuffer:this.eventBuffer,recentEvents:this.recentEvents,lineageRecent:[...this.lineageRecent.entries()],archive:this.archive.dump(),checkpoints:this.checkpoints,checkpointDone:[...this.checkpointDone],noveltyArchive:this.noveltyArchive,fixedAgeN:this.fixedAgeN,fixedAgeOffspring:this.fixedAgeOffspring,fixedAgeReproduced:this.fixedAgeReproduced,completedN:this.completedN,completedOffspring:this.completedOffspring,completedReproduced:this.completedReproduced,ecology:this.ecology,matureExposure:this.matureExposure,lastClusterCount:this.lastClusterCount,cohortStats:this.cohortStats,mutationStats:this.mutationStats,startObserverTime:this.startObserverTime};}
  static load(o){if(o.protocolId!==PROTOCOL_ID)throw new Error('Protocol mismatch: '+o.protocolId);const w=Object.create(World.prototype);Object.assign(w,o);w.rngInit=RNG.load(o.rngInit);w.rngEnvironment=RNG.load(o.rngEnvironment);w.agents=o.agents.map(x=>new Agent(x));w.lineageRecent=new Map(o.lineageRecent||[]);w.archive=MultiResolutionArchive.load(o.archive);w.checkpointDone=new Set(o.checkpointDone||[]);w.ancestorGenome=cloneGenome(o.ancestorGenome);w.cohortStats=o.cohortStats||{};w.mutationStats=o.mutationStats||{birthsWithMutations:0,totalChanges:0,byType:{trait:0,sensor:0,bias:0,weight:0,structure:0},byAction:{},byTarget:{}};return w;}
}

function runAssay(genome,seed,opts={}){const w=new World({seed,founderGenome:genome,founderCount:opts.founderCount||24,mutationEnabled:false,reproductionMode:opts.reproductionMode||'asexual',objectsEnabled:opts.objectsEnabled??false,chemicalEnabled:opts.chemicalEnabled??false});const ticks=opts.ticks||6000;for(let i=0;i<ticks&&!w.extinct&&!w.technicalFailure;i++)w.step();const m=w.metrics();return{seed,ticks:w.tick,genomeHash:genomeHash(genome),births:m.births,population:m.population,extinct:m.extinct,meanOffspringFixedAge:m.meanOffspringFixedAge,reproducedFixedAgeFraction:m.reproducedFixedAgeFraction,reproRate:m.reproductionRatePer1000MatureTicks,meanEnergy:m.meanEnergy,stateHash:w.stateHash()};}

function commonGarden(genomes,ancestor,assaySeeds=[91001,91002,91003],opts={}){const anc=assaySeeds.map(s=>runAssay(ancestor,s,opts)),evo=[];for(const g of genomes)for(const s of assaySeeds)evo.push(runAssay(g,s,opts));const aMap=new Map(anc.map(x=>[x.seed,x.reproRate])),ratios=evo.map(x=>({seed:x.seed,genomeHash:x.genomeHash,ratio:aMap.get(x.seed)>0?x.reproRate/aMap.get(x.seed):NaN})).filter(x=>Number.isFinite(x.ratio));return{ancestor:anc,evolved:evo,ratios,meanRatio:mean(ratios.map(x=>x.ratio)),meanLogRatio:mean(ratios.filter(x=>x.ratio>0).map(x=>Math.log(x.ratio)))};}

function knockoutGenome(g,connectionId){const x=cloneGenome(g),c=x.connections.find(c=>c.id===connectionId);if(c)c.enabled=false;return x;}
function oneStepMutant(g,seed,index){const x=cloneGenome(g),r=new RNG(eventSeed(seed,'neighborhood',0,index));const mode=r.int(4);if(mode===0){const k=TraitKeys[r.int(TraitKeys.length)],old=x.traits[k];x.traits[k]=clampTrait(k,old+r.gauss()*Protocol.mutation.traitSigma*Math.max(.2,Math.abs(old)));}else if(mode===1&&x.connections.length){x.connections[r.int(x.connections.length)].weight+=r.gauss()*Protocol.mutation.weightSigma;}else if(mode===2&&x.hidden.length){x.hidden[r.int(x.hidden.length)].bias+=r.gauss()*Protocol.mutation.biasSigma;}else if(x.sensors.length){const s=x.sensors[r.int(x.sensors.length)];s.angle=wrap(s.angle+r.gauss()*.18,TAU);}return sanitizeGenome(x);}
function mutationalNeighborhood(g,seed=99001,n=64,assayOpts={ticks:3500,founderCount:16}){const base=runAssay(g,seed,assayOpts),rows=[];for(let i=0;i<n;i++){const m=oneStepMutant(g,seed,i),r=runAssay(m,seed,assayOpts);rows.push({i,genomeHash:genomeHash(m),reproRate:r.reproRate,relative:base.reproRate>0?r.reproRate/base.reproRate:NaN});}const rel=rows.map(x=>x.relative).filter(Number.isFinite);return{base,rows,beneficial:rel.filter(x=>x>1.02).length,neutral:rel.filter(x=>x>=.98&&x<=1.02).length,deleterious:rel.filter(x=>x<.98).length,meanRelative:mean(rel)};}

function selfTest(){const results=[];function test(name,fn){try{const d=fn();results.push({name,ok:!!d,detail:typeof d==='string'?d:''});}catch(e){results.push({name,ok:false,detail:String(e.message||e)});}}
  test('same seed deterministic',()=>{const a=new World({seed:12345}),b=new World({seed:12345});for(let i=0;i<600;i++){a.step();b.step();}return a.stateHash()===b.stateHash()||`A ${a.stateHash()} B ${b.stateHash()}`;});
  test('different seed diverges',()=>{const a=new World({seed:12345}),b=new World({seed:12346});for(let i=0;i<250;i++){a.step();b.step();}return a.stateHash()!==b.stateHash();});
  test('save/load continuation deterministic',()=>{const a=new World({seed:222});for(let i=0;i<300;i++)a.step();const b=World.load(JSON.parse(JSON.stringify(a.dump())));for(let i=0;i<200;i++){a.step();b.step();}return a.stateHash()===b.stateHash()||`A ${a.stateHash()} B ${b.stateHash()}`;});
  test('mutation-off keeps ancestor genotype with asexual control',()=>{const w=new World({seed:333,mutationEnabled:false,reproductionMode:'asexual',objectsEnabled:false,chemicalEnabled:false});for(let i=0;i<1200&&!w.extinct;i++)w.step();return w.agents.every(a=>genomeHash(a.genome)===w.ancestorHash);});
  test('resource flux is population independent',()=>Protocol.resources.primaryFluxPerTick===0.22&&Protocol.ecology.populationFeedback===false);
  test('no semantic ray sensor types',()=>founderGenome().sensors.every(s=>Object.keys(s).every(k=>['id','angle','range','gain'].includes(k))));
  test('observer archive does not affect state hash',()=>{const a=new World({seed:444}),b=new World({seed:444});b.archive.add=()=>{};for(let i=0;i<400;i++){a.step();b.step();}return a.stateHash()===b.stateHash();});
  return{ok:results.every(x=>x.ok),results,protocolId:PROTOCOL_ID,protocolHash:PROTOCOL_HASH,engineHash:ENGINE_HASH};
}

return{ENGINE_VERSION,PROTOCOL_ID,PROTOCOL_HASH,ENGINE_HASH,Protocol,Limits,RNG,World,Agent,founderGenome,phenotype,genomeHash,genomeDistance,cloneGenome,runAssay,commonGarden,knockoutGenome,mutationalNeighborhood,selfTest,helpers:{clamp,mean,median,variance,eventSeed,keyed01,wrap,dist2}};
});
